import assert from 'node:assert/strict';
import { mergeStatementEvidence } from '../lib/statement-evidence.js';
import { createCanonicalEvidence } from '../lib/financial-evidence.js';

const date = '2025-03-31T00:00:00.000Z';
const meta = (sourceKey, value, overrides = {}) => createCanonicalEvidence({ source: 'YAHOO_FINANCE', sourceKey, value, issuer: 'Test Issuer', ticker: 'TEST.NS', reportingDate: date, reportingPeriod: '2025-03-31', periodType: 'ANNUAL', statementScope: 'CONSOLIDATED', unit: 'INR_CRORE', currency: 'INR', reportedOrDerived: 'REPORTED', status: 'PROVIDER_RETURNED', ...overrides });
const raw = {
  income: { revenue:{status:'PROVIDER_RETURNED',value:1000,key:'totalRevenue',date}, ebitda:{status:'PROVIDER_RETURNED',value:220,key:'EBITDA',date}, ebit:{status:'PROVIDER_RETURNED',value:200,key:'EBIT',date}, eps:{status:'PROVIDER_RETURNED',value:15,key:'dilutedEPS',date}, netIncome:{status:'PROVIDER_RETURNED',value:100,key:'netIncome',date}, interestExpense:{status:'PROVIDER_RETURNED',value:20,key:'interestExpense',date} },
  balance: { totalAssets:{status:'PROVIDER_RETURNED',value:1500,key:'totalAssets',date}, totalDebt:{status:'PROVIDER_RETURNED',value:250,key:'totalDebt',date}, cash:{status:'PROVIDER_RETURNED',value:75,key:'cashCashEquivalentsAndShortTermInvestments',date}, equity:{status:'PROVIDER_RETURNED',value:1250,key:'stockholdersEquity',date}, currentAssets:{status:'PROVIDER_RETURNED',value:300,key:'currentAssets',date}, currentLiabilities:{status:'PROVIDER_RETURNED',value:133,key:'currentLiabilities',date}, workingCapital:{status:'PROVIDER_RETURNED',value:167,key:'workingCapital',date}, ordinaryShares:{status:'PROVIDER_RETURNED',value:100,key:'ordinarySharesNumber',date} },
  cash: { operatingCashFlow:{status:'PROVIDER_RETURNED',value:180,key:'operatingCashFlow',date}, investingCashFlow:{status:'PROVIDER_RETURNED',value:-120,key:'investingCashFlow',date}, financingCashFlow:{status:'PROVIDER_RETURNED',value:-80,key:'financingCashFlow',date}, changeInCash:{status:'PROVIDER_RETURNED',value:-20,key:'changesInCash',date}, freeCashFlow:{status:'PROVIDER_RETURNED',value:175,key:'freeCashFlow',date}, capitalExpenditure:{status:'PROVIDER_RETURNED',value:-55,key:'capitalExpenditure',date}, dividends:{status:'PROVIDER_RETURNED',value:-40,key:'commonStockDividendPaid',date}, stockBasedCompensation:{status:'PROVIDER_RETURNED',value:12,key:'stockBasedCompensation',date} }
};
const canonicalEvidence={byId:{},observations:{}};
for(const fields of Object.values(raw)) for(const [field,item] of Object.entries(fields)){const e=meta(item.key,item.value);canonicalEvidence.byId[e.evidenceId]=e;canonicalEvidence.observations[field]=e.evidenceId;}
const evidence={provider:'Yahoo Finance fundamentalsTimeSeries',ticker:'TEST.NS',period:'annual / 12M',coverage:{income:true,balanceSheet:true,cashFlow:true},evidence:raw,canonicalEvidence,history:{incomeYears:4,balanceYears:4,cashFlowYears:4},errors:{income:null,balance:null,cash:null}};
const merged=mergeStatementEvidence({current:{},derived:{},rawAvailability:{}},evidence);
assert.equal(merged.current.totalDebt,250);assert.equal(merged.current.revenue,1000);assert.equal(merged.current.ebitda,220);
assert.ok(merged.evidence.fields.totalDebt);assert.equal(merged.evidence.byId[merged.evidence.fields.totalDebt].sourceKey,'totalDebt');assert.equal(merged.evidence.byId[merged.evidence.fields.totalDebt].value,250);assert.equal(merged.evidence.byId[merged.evidence.fields.totalDebt].reportingDate,date);assert.equal(merged.evidence.byId[merged.evidence.fields.totalDebt].periodType,'ANNUAL');assert.equal(merged.evidence.byId[merged.evidence.fields.totalDebt].statementScope,'CONSOLIDATED');assert.equal(merged.evidence.byId[merged.evidence.fields.totalDebt].unit,'INR_CRORE');assert.equal(merged.evidence.byId[merged.evidence.fields.totalDebt].currency,'INR');assert.equal(merged.evidence.byId[merged.evidence.fields.totalDebt].reportedOrDerived,'REPORTED');
assert.equal(merged.derived.debtToEquityFromStatements,0.2);assert.equal(merged.derived.currentRatioFromStatements,300/133);assert.equal(merged.derived.fcfConversion,175);assert.equal(merged.derived.fcfMargin,17.5);assert.equal(merged.derived.netDebtToEbitda,(250-75)/220);assert.equal(merged.derived.interestCoverage,10);assert.equal(merged.derived.roeFromStatements,8);assert.equal(merged.derived.roaFromStatements,100/1500*100);assert.equal(merged.derived.roceFromStatements,200/1500*100);assert.equal(merged.derived.workingCapital,167);
assert.equal(merged.current.changeInCash,-20);assert.equal(merged.statementEvidence,evidence);
const incompatible=(overrides={})=>{const debt=meta('totalDebt',250);const equity=meta('stockholdersEquity',1250,overrides);return mergeStatementEvidence({current:{},derived:{}},{coverage:{income:true,balanceSheet:true,cashFlow:false},evidence:{balance:{totalDebt:raw.balance.totalDebt,equity:raw.balance.equity}},canonicalEvidence:{byId:{[debt.evidenceId]:debt,[equity.evidenceId]:equity},fields:{totalDebt:debt.evidenceId,equity:equity.evidenceId}}});};
assert.equal(incompatible({reportingDate:'2026-03-31T00:00:00.000Z'}).derived.debtToEquityFromStatements,null);assert.equal(incompatible({periodType:'QUARTERLY'}).derived.debtToEquityFromStatements,null);assert.equal(incompatible({periodType:'TTM'}).derived.debtToEquityFromStatements,null);assert.equal(incompatible({statementScope:'STANDALONE'}).derived.debtToEquityFromStatements,null);assert.equal(incompatible({statementScope:null}).derived.debtToEquityFromStatements,null);assert.equal(incompatible({unit:'INR_MILLION'}).derived.debtToEquityFromStatements,null);assert.equal(incompatible({unit:null}).derived.debtToEquityFromStatements,null);assert.equal(incompatible({currency:'USD'}).derived.debtToEquityFromStatements,null);assert.equal(incompatible({currency:null}).derived.debtToEquityFromStatements,null);assert.equal(incompatible({issuer:'Other Issuer'}).derived.debtToEquityFromStatements,null);assert.equal(incompatible({ticker:'OTHER.NS'}).derived.debtToEquityFromStatements,null);
const unavailable=mergeStatementEvidence({current:{},derived:{}},{coverage:{income:true,balanceSheet:true,cashFlow:true},evidence:{balance:{totalAssets:{status:'PROVIDER_DID_NOT_RETURN',value:null,key:null,date:null},totalDebt:{status:'PROVIDER_DID_NOT_RETURN',value:null,key:null,date:null},cash:{status:'PROVIDER_DID_NOT_RETURN',value:null,key:null,date:null},equity:{status:'PROVIDER_DID_NOT_RETURN',value:null,key:null,date:null},currentAssets:{status:'PROVIDER_DID_NOT_RETURN',value:null,key:null,date:null},currentLiabilities:{status:'PROVIDER_DID_NOT_RETURN',value:null,key:null,date:null},workingCapital:{status:'PROVIDER_DID_NOT_RETURN',value:null,key:null,date:null},ordinaryShares:{status:'PROVIDER_DID_NOT_RETURN',value:null,key:null,date:null}},cash:{operatingCashFlow:{status:'PROVIDER_DID_NOT_RETURN',value:null,key:null,date:null},investingCashFlow:{status:'PROVIDER_DID_NOT_RETURN',value:null,key:null,date:null},freeCashFlow:{status:'PROVIDER_DID_NOT_RETURN',value:null,key:null,date:null},capitalExpenditure:{status:'PROVIDER_DID_NOT_RETURN',value:null,key:null,date:null}}}});
for(const field of ['totalAssets','totalDebt','cash','equity','currentAssets','currentLiabilities','workingCapital','ordinaryShares','operatingCashFlow','investingCashFlow','freeCashFlow','capitalExpenditure']){assert.equal(unavailable.current[field],null);assert.notEqual(unavailable.current[field],0);}
assert.equal(unavailable.derived.debtToEquityFromStatements,null);assert.equal(unavailable.derived.currentRatioFromStatements,null);assert.equal(unavailable.derived.fcfConversion,null);assert.equal(unavailable.derived.fcfMargin,null);assert.equal(unavailable.derived.netDebtToEbitda,null);assert.equal(unavailable.derived.roaFromStatements,null);assert.equal(unavailable.derived.roceFromStatements,null);assert.equal(unavailable.derived.workingCapital,null);
const preexisting=mergeStatementEvidence({current:{totalDebt:999,equity:100},derived:{}},{...evidence,canonicalEvidence:{byId:evidence.canonicalEvidence.byId,observations:evidence.canonicalEvidence.observations}});assert.equal(preexisting.current.totalDebt,999);assert.equal(preexisting.evidence.fields.totalDebt,undefined);assert.equal(preexisting.derived.debtToEquityFromStatements,null);
const sameValueDifferentObservation=mergeStatementEvidence({current:{totalDebt:250,equity:100},derived:{}},{...evidence,canonicalEvidence:{byId:evidence.canonicalEvidence.byId,observations:evidence.canonicalEvidence.observations}});assert.equal(sameValueDifferentObservation.current.totalDebt,250);assert.equal(sameValueDifferentObservation.evidence.fields.totalDebt,undefined);assert.equal(sameValueDifferentObservation.derived.debtToEquityFromStatements,null);
const endCashOnly=mergeStatementEvidence({current:{},derived:{}},{coverage:{income:false,balanceSheet:false,cashFlow:true},evidence:{cash:{changeInCash:{status:'PROVIDER_DID_NOT_RETURN',value:null,key:null,date:null},endCashPosition:{status:'PROVIDER_RETURNED',value:999,key:'endCashPosition',date}}}});assert.equal(endCashOnly.current.changeInCash,null);assert.equal(endCashOnly.current.endCashPosition,undefined);
console.log('statement-evidence.unit: PASS');
