import assert from 'node:assert/strict';
import { resolveValuationEvidence } from '../lib/valuation-evidence-authority.js';

const record = (id, value, extra = {}) => ({ evidenceId:id, value, source:'TEST_PROVIDER', sourceKey:`key.${id}`, ticker:'TEST.NS', issuer:'TEST LTD', reportingDate:'2026-03-31', reportingPeriod:'FY2026', periodType:'ANNUAL', statementScope:'CONSOLIDATED', unit:'INR', currency:'INR', reportedOrDerived:'REPORTED', status:'VERIFIED', retrievedAt:'2026-09-01T00:00:00.000Z', ...extra });
const make = (overrides = {}) => {
  const forward = record('ev_forward', 8.3, { periodType:'FORWARD', reportingPeriod:'FY2027E' });
  const price = record('ev_price', 150, { periodType:'CURRENT', reportingDate:'2026-09-01', reportingPeriod:'CURRENT' });
  return resolveValuationEvidence({ valuation:{fairValue:180,currentPrice:150,verdict:'ATTRACTIVE'}, valuationMetricLineage:{ fairValue:{value:180,inputMetrics:['forwardEPS'],inputLineage:{forwardEPS:{value:8.3,evidenceIds:['ev_forward'],qualification:'FORWARD',periodSemantics:{periodType:'FORWARD'}}}}, forwardEPS:{value:8.3,evidenceIds:['ev_forward'],qualification:'FORWARD',periodSemantics:{periodType:'FORWARD'}}, currentPrice:{evidence:price}}, financials:{canonicalEvidence:{byId:{ev_forward:forward,ev_price:price}}}, ticker:'TEST.NS', ...overrides });
};

assert.equal(make().valuationEvidenceStatus,'VERIFIED');
assert.equal(make().eligibleForInvestmentReadiness,true);
assert.equal(make({financials:{canonicalEvidence:{byId:{ev_forward:record('ev_forward',8.3,{status:'PROVIDER_RETURNED',periodType:'FORWARD',reportingPeriod:'FY2027E'}),ev_price:record('ev_price',150,{periodType:'CURRENT',reportingDate:'2026-09-01',reportingPeriod:'CURRENT'})}}}}).valuationEvidenceStatus,'INSUFFICIENT_EVIDENCE');
assert.equal(make({financials:{canonicalEvidence:{byId:{ev_forward:record('ev_forward',8.3,{status:'PROVIDER_RETURNED',periodType:'FORWARD',reportingPeriod:'FY2027E'}),ev_price:record('ev_price',150,{periodType:'CURRENT',reportingDate:'2026-09-01',reportingPeriod:'CURRENT'})}}}}).eligibleForInvestmentReadiness,false);
assert.equal(make({financials:{canonicalEvidence:{byId:{}}}}).valuationEvidenceStatus,'INSUFFICIENT_EVIDENCE');
assert.equal(make({valuationMetricLineage:{...make().valuationMetricLineage,fairValue:{...make().valuationMetricLineage.fairValue,inputLineage:{forwardEPS:{value:9,evidenceIds:['ev_forward'],qualification:'FORWARD',periodSemantics:{periodType:'FORWARD'}}}}}}).valuationEvidenceStatus,'INSUFFICIENT_EVIDENCE');
assert.equal(make({financials:{canonicalEvidence:{byId:{ev_forward:record('ev_forward',8.3,{ticker:'OTHER.NS',periodType:'FORWARD',reportingPeriod:'FY2027E'}),ev_price:record('ev_price',150,{periodType:'CURRENT',reportingDate:'2026-09-01',reportingPeriod:'CURRENT'})}}}}).valuationEvidenceStatus,'INSUFFICIENT_EVIDENCE');
assert.equal(make({financials:{canonicalEvidence:{byId:{ev_forward:record('ev_forward',8.3,{issuer:'OTHER LTD',periodType:'FORWARD',reportingPeriod:'FY2027E'}),ev_price:record('ev_price',150,{periodType:'CURRENT',reportingDate:'2026-09-01',reportingPeriod:'CURRENT'})}}}}).valuationEvidenceStatus,'INSUFFICIENT_EVIDENCE');
assert.equal(make({financials:{canonicalEvidence:{byId:{ev_forward:record('ev_forward',8.3,{periodType:'FORWARD',reportingPeriod:'FY2026'}),ev_price:record('ev_price',150,{periodType:'CURRENT',reportingDate:'2026-09-01',reportingPeriod:'CURRENT'})}}}}).valuationEvidenceStatus,'INSUFFICIENT_EVIDENCE');
assert.equal(make({valuationMetricLineage:{...make().valuationMetricLineage,fairValue:{...make().valuationMetricLineage.fairValue,inputMetrics:['trailingEPS'],inputLineage:{trailingEPS:{value:7.5,evidenceIds:['ev_ttm'],qualification:'TTM',periodSemantics:{periodType:'TTM'}}}},trailingEPS:{value:7.5,evidenceIds:['ev_ttm'],qualification:'TTM',periodSemantics:{periodType:'TTM'}}},financials:{canonicalEvidence:{byId:{ev_ttm:record('ev_ttm',7.5,{periodType:'TTM',reportingPeriod:'TTM'})}}}}).valuationEvidenceStatus,'VERIFIED');
assert.equal(make({valuationMetricLineage:{...make().valuationMetricLineage,fairValue:{...make().valuationMetricLineage.fairValue,inputLineage:{forwardEPS:{value:8.3,evidenceIds:['ev_forward'],qualification:'ANNUAL',periodSemantics:{periodType:'ANNUAL'}}}}}}).valuationEvidenceStatus,'INSUFFICIENT_EVIDENCE');
assert.equal(make({valuationMetricLineage:{...make().valuationMetricLineage,fairValue:{...make().valuationMetricLineage.fairValue,inputMetrics:[]}}}).valuationEvidenceStatus,'INSUFFICIENT_EVIDENCE');
const metadataLineage={...make().valuationMetricLineage,fairValue:{...make().valuationMetricLineage.fairValue,inputLineage:{forwardEPS:{value:8.3,evidenceIds:['ev_forward'],qualification:'FORWARD',periodSemantics:{periodType:'FORWARD'},statementScope:'OTHER',unit:'USD',currency:'USD'}}}};
assert.equal(make({valuationMetricLineage:metadataLineage}).valuationEvidenceStatus,'INSUFFICIENT_EVIDENCE');
assert.equal(make({financials:{canonicalEvidence:{byId:{ev_forward:record('ev_forward',8.3,{periodType:'FORWARD',reportingPeriod:'FY2027E',statementScope:'CONSOLIDATED',unit:'USD',currency:'USD'}),ev_price:record('ev_price',150,{periodType:'CURRENT',reportingDate:'2026-09-01',reportingPeriod:'CURRENT'})}}}}).valuationEvidenceStatus,'VERIFIED');
assert.equal(make({valuation:{fairValue:180,currentPrice:151,verdict:'ATTRACTIVE'}}).eligibleForInvestmentReadiness,false);

assert.equal(make({financials:{canonicalEvidence:{byId:{ev_forward:record('ev_forward',8.3,{statementScope:null,periodType:'FORWARD',reportingPeriod:'FY2027E'}),ev_price:record('ev_price',150,{periodType:'CURRENT',reportingDate:'2026-09-01',reportingPeriod:'CURRENT'})}}}}).valuationEvidenceStatus,'INSUFFICIENT_EVIDENCE');
assert.equal(make({financials:{canonicalEvidence:{byId:{ev_forward:record('ev_forward',8.3,{unit:null,periodType:'FORWARD',reportingPeriod:'FY2027E'}),ev_price:record('ev_price',150,{periodType:'CURRENT',reportingDate:'2026-09-01',reportingPeriod:'CURRENT'})}}}}).valuationEvidenceStatus,'INSUFFICIENT_EVIDENCE');
assert.equal(make({financials:{canonicalEvidence:{byId:{ev_forward:record('ev_forward',8.3,{currency:null,periodType:'FORWARD',reportingPeriod:'FY2027E'}),ev_price:record('ev_price',150,{periodType:'CURRENT',reportingDate:'2026-09-01',reportingPeriod:'CURRENT'})}}}}).valuationEvidenceStatus,'INSUFFICIENT_EVIDENCE');
assert.equal(make({financials:{canonicalEvidence:{byId:{ev_forward:record('ev_forward',8.3,{source:null,periodType:'FORWARD',reportingPeriod:'FY2027E'}),ev_price:record('ev_price',150,{periodType:'CURRENT',reportingDate:'2026-09-01',reportingPeriod:'CURRENT'})}}}}).valuationEvidenceStatus,'INSUFFICIENT_EVIDENCE');
assert.equal(make({financials:{canonicalEvidence:{byId:{ev_forward:record('ev_forward',8.3,{retrievedAt:null,periodType:'FORWARD',reportingPeriod:'FY2027E'}),ev_price:record('ev_price',150,{periodType:'CURRENT',reportingDate:'2026-09-01',reportingPeriod:'CURRENT'})}}}}).valuationEvidenceStatus,'INSUFFICIENT_EVIDENCE');

const derivedIncomplete = record('ev_derived', 8.3, { reportedOrDerived:'DERIVED', status:'VERIFIED_COMPATIBLE_STATEMENT_INPUTS', periodType:'FORWARD', reportingPeriod:'FY2027E' });
assert.equal(make({valuationMetricLineage:{...make().valuationMetricLineage,fairValue:{...make().valuationMetricLineage.fairValue,inputLineage:{forwardEPS:{value:8.3,evidenceIds:['ev_derived'],qualification:'FORWARD',periodSemantics:{periodType:'FORWARD'}}}}},financials:{canonicalEvidence:{byId:{ev_derived:derivedIncomplete}}}}).valuationEvidenceStatus,'INSUFFICIENT_EVIDENCE');

console.log('valuation-evidence-authority.unit: PASS');
