import { verifiedHistory } from './market-data-provider.js';
const avg=(a,p)=>a.length>=p?a.slice(-p).reduce((s,x)=>s+x,0)/p:null;
const ema=(a,p)=>{if(a.length<p)return null;let e=avg(a.slice(0,p),p),k=2/(p+1);for(let i=p;i<a.length;i++)e=a[i]*k+e*(1-k);return e};
const norm=s=>{s=String(s||'').trim().toUpperCase();return s.endsWith('.NS')||s.endsWith('.BO')?s:`${s}.NS`};
function rsi(c,p=14){if(c.length<=p)return null;let g=0,l=0;for(let i=1;i<=p;i++){const d=c[i]-c[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=p;l/=p;for(let i=p+1;i<c.length;i++){const d=c[i]-c[i-1];g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p}return l?100-100/(1+g/l):100}
function atr(r,p=14){if(r.length<=p)return null;const tr=[];for(let i=1;i<r.length;i++){const x=r[i],q=r[i-1];tr.push(Math.max(x.h-x.l,Math.abs(x.h-q.c),Math.abs(x.l-q.c)))}let a=avg(tr.slice(0,p),p);for(let i=p;i<tr.length;i++)a=(a*(p-1)+tr[i])/p;return a}
function signal(rows,i){const h=rows.slice(0,i+1),c=h.map(x=>x.c),p=c.at(-1),e20=ema(c,20),e50=ema(c,50),e200=ema(c,200),rs=rsi(c),a=atr(h),av=avg(h.map(x=>x.v),20),rv=av?h.at(-1).v/av:null;if(!e50||!a||rs==null||rv==null)return null;const bull=p>e20&&e20>e50&&(e200==null||e50>e200)&&rs>=55&&rs<=72&&rv>=1;const bear=p<e20&&e20<e50&&(e200==null||e50<e200)&&rs<=45&&rv>=1;return bull?{side:'LONG'}:bear?{side:'SHORT'}:null}
const DEFAULT_COSTS={buyTransactionPct:0.115,sellTransactionPct:0.115,slippagePct:0.05};
const pct=(value,p)=>value*p/100;
function applyEntryCosts(entry,side,costs){const slip=pct(entry,costs.slippagePct);const transaction=pct(entry,costs.buyTransactionPct);return side==='LONG'?entry+slip+transaction:entry-slip-transaction}
function applyExitCosts(exit,side,costs){const slip=pct(exit,costs.slippagePct);const transaction=pct(exit,costs.sellTransactionPct);return side==='LONG'?exit-slip-transaction:exit+slip+transaction}
function stopFill(q,stop,side){const open=q.o??q.c;if(side==='LONG')return open<=stop?open:stop;return open>=stop?open:stop}
function targetFill(q,target,side){const open=q.o??q.c;if(side==='LONG')return open>=target?open:target;return open<=target?open:target}
function run(rows,horizon=10,costs=DEFAULT_COSTS){const trades=[];let equity=1,peak=1,maxDD=0,i=60;while(i<rows.length-horizon-1){const s=signal(rows,i);if(!s){i++;continue}const entryBar=rows[i+1],rawEntry=entryBar.o??entryBar.c,a=atr(rows.slice(0,i+1));if(!a){i++;continue}const entry=applyEntryCosts(rawEntry,s.side,costs),risk=1.5*a,stop=s.side==='LONG'?entry-risk:entry+risk,target=s.side==='LONG'?entry+2*risk:entry-2*risk;let rawExit=rows[Math.min(i+horizon,rows.length-1)].c,exitIndex=Math.min(i+horizon,rows.length-1),reason='TIME';for(let j=i+1;j<=Math.min(i+horizon,rows.length-1);j++){const q=rows[j];if(s.side==='LONG'){if(q.l<=stop){rawExit=stopFill(q,stop,s.side);exitIndex=j;reason='STOP';break}if(q.h>=target){rawExit=targetFill(q,target,s.side);exitIndex=j;reason='TARGET';break}}else{if(q.h>=stop){rawExit=stopFill(q,stop,s.side);exitIndex=j;reason='STOP';break}if(q.l<=target){rawExit=targetFill(q,target,s.side);exitIndex=j;reason='TARGET';break}}}const exit=applyExitCosts(rawExit,s.side,costs),ret=s.side==='LONG'?(exit-entry)/entry:(entry-exit)/entry;equity*=1+ret;peak=Math.max(peak,equity);maxDD=Math.max(maxDD,(peak-equity)/peak);trades.push({signalIndex:i,entryIndex:i+1,exitIndex,side:s.side,entry:+entry.toFixed(4),rawEntry:+rawEntry.toFixed(4),exit:+exit.toFixed(4),rawExit:+rawExit.toFixed(4),returnPct:+(ret*100).toFixed(2),reason});i=exitIndex+1}const wins=trades.filter(x=>x.returnPct>0),losses=trades.filter(x=>x.returnPct<=0),grossWin=wins.reduce((s,x)=>s+x.returnPct,0),grossLoss=Math.abs(losses.reduce((s,x)=>s+x.returnPct,0));return{horizonDays:horizon,trades:trades.length,wins:wins.length,losses:losses.length,winRate:trades.length?wins.length/trades.length*100:null,totalReturnPct:(equity-1)*100,avgTradePct:trades.length?trades.reduce((s,x)=>s+x.returnPct,0)/trades.length:null,profitFactor:grossLoss?grossWin/grossLoss:null,maxDrawdownPct:maxDD*100,expectancyPct:trades.length?trades.reduce((s,x)=>s+x.returnPct,0)/trades.length:null,latestTrades:trades.slice(-10)}}
export async function backtestSymbol(symbol,{days=1800,horizons=[5,10,20],costs=DEFAULT_COSTS}={}){const ticker=norm(symbol);let d;try{d=await verifiedHistory(ticker,{interval:'1d',days,minBars:200})}catch(error){const text=String(error?.message||error||'');if(/INSUFFICIENT_VERIFIED_PRICE_HISTORY|NO DATA FOUND|SYMBOL MAY BE DELISTED|INSUFFICIENT MARKET DATA/i.test(text))return{success:false,status:'DATA_UNAVAILABLE',symbol:ticker.replace(/\.NS$|\.BO$/,''),source:'Yahoo Finance chart API',bars:0,errorCode:'INSUFFICIENT_VERIFIED_PRICE_HISTORY',error:'Verified historical data is unavailable for this symbol.',policy:{fabricatedData:false,fallback:'none'}};throw error}return{success:true,symbol:ticker.replace(/\.NS$|\.BO$/,''),source:d.source,latest:d.latest,bars:d.bars,results:horizons.map(h=>run(d.rows,h,costs)),policy:{lookAheadBias:false,entry:'next available bar open with adverse slippage + buy transaction costs',exit:'first stop/target hit or horizon close with adverse slippage + sell transaction costs',gapHandling:'stop/target fills use next bar open when price gaps through the level; otherwise level price',sameBarConflict:'stop is evaluated before target (conservative)',costModel:{buyTransactionPct:costs.buyTransactionPct,sellTransactionPct:costs.sellTransactionPct,slippagePct:costs.slippagePct},data:'verified provider OHLCV only',fabricatedData:false}}}
