import YahooFinance from 'yahoo-finance2';
const yf=new YahooFinance();
const n=v=>typeof v==='number'&&Number.isFinite(v)?v:v&&Number.isFinite(v.raw)?v.raw:null;
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,Number.isFinite(v)?v:a));
const pct=(a,b)=>a!=null&&b?((a/b)-1)*100:null;
const sma=(a,p)=>a.length>=p?a.slice(-p).reduce((s,x)=>s+x,0)/p:null;
const ema=(a,p)=>{if(a.length<p)return null;let e=sma(a.slice(0,p),p),k=2/(p+1);for(let i=p;i<a.length;i++)e=a[i]*k+e*(1-k);return e};
function rsi(a,p=14){if(a.length<=p)return null;let g=0,l=0;for(let i=1;i<=p;i++){let d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=p;l/=p;for(let i=p+1;i<a.length;i++){let d=a[i]-a[i-1];g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p}return l===0?100:100-100/(1+g/l)}
function atr(rows,p=14){if(rows.length<=p)return null;let tr=[];for(let i=1;i<rows.length;i++){let x=rows[i],q=rows[i-1];tr.push(Math.max(x.h-x.l,Math.abs(x.h-q.c),Math.abs(x.l-q.c)))}let a=sma(tr.slice(0,p),p);for(let i=p;i<tr.length;i++)a=(a*(p-1)+tr[i])/p;return a}
function macd(a){if(a.length<35)return null;let series=[];for(let i=26;i<=a.length;i++){let z=a.slice(0,i);series.push(ema(z,12)-ema(z,26))}let line=series.at(-1),signal=ema(series,9);return{line,signal,histogram:signal==null?null:line-signal};}
function bollinger(a,p=20,m=2){if(a.length<p)return null;let mean=sma(a,p),sd=Math.sqrt(a.slice(-p).reduce((s,x)=>s+(x-mean)**2,0)/p);return{middle:mean,upper:mean+m*sd,lower:mean-m*sd,width:mean?((2*m*sd)/mean)*100:null,percentB:sd?((a.at(-1)-(mean-m*sd))/(2*m*sd)):null}}
function stoch(rows,p=14){if(rows.length<p)return null;let r=rows.slice(-p),hi=Math.max(...r.map(x=>x.h)),lo=Math.min(...r.map(x=>x.l)),k=hi===lo?50:(rows.at(-1).c-lo)/(hi-lo)*100;return{k,d:k}}
function obv(rows){let v=0;for(let i=1;i<rows.length;i++)v+=rows[i].c>rows[i-1].c?rows[i].v:rows[i].c<rows[i-1].c?-rows[i].v:0;return v}
function adx(rows,p=14){if(rows.length<2*p+2)return null;let tr=[],pd=[],md=[];for(let i=1;i<rows.length;i++){let x=rows[i],q=rows[i-1];tr.push(Math.max(x.h-x.l,Math.abs(x.h-q.c),Math.abs(x.l-q.c)));let up=x.h-q.h,dn=q.l-x.l;pd.push(up>dn&&up>0?up:0);md.push(dn>up&&dn>0?dn:0)}let t=sma(tr,p),pdm=sma(pd,p),mdm=sma(md,p),dx=[];for(let i=p;i<tr.length;i++){t=t-t/p+tr[i];pdm=pdm-pdm/p+pd[i];mdm=mdm-mdm/p+md[i];let pi=t?100*pdm/t:0,mi=t?100*mdm/t:0;dx.push(pi+mi?100*Math.abs(pi-mi)/(pi+mi):0)}return dx.length>=p?sma(dx.slice(-p),p):null}
const norm=s=>{s=String(s||'').trim().toUpperCase();return s.endsWith('.NS')||s.endsWith('.BO')?s:`${s}.NS`};
export const DEFAULT_UNIVERSE=['RELIANCE','TCS','HDFCBANK','ICICIBANK','INFY','BHARTIARTL','SBIN','LICI','ITC','HINDUNILVR','LT','BAJFINANCE','HCLTECH','MARUTI','M&M','KOTAKBANK','SUNPHARMA','AXISBANK','ULTRACEMCO','TITAN','ADANIENT','ADANIPORTS','NTPC','ONGC','POWERGRID','TATASTEEL','JSWSTEEL','NESTLEIND','ASIANPAINT','WIPRO','TECHM','TATAMOTORS','BAJAJFINSV','COALINDIA','HINDALCO','TRENT','EICHERMOT','GRASIM','CIPLA','DRREDDY','DIVISLAB','APOLLOHOSP','SBILIFE','HDFCLIFE','BAJAJ-AUTO','HEROMOTOCO','TATACONSUM','BEL','HAL','INDUSINDBK'];
async function daily(symbol){let raw=await yf.chart(norm(symbol),{period1:new Date(Date.now()-900*86400000),period2:new Date(),interval:'1d',events:'div,splits',return:'object'});let q=Array.isArray(raw?.quotes)?raw.quotes:[],rows=q.map(x=>({date:x.date instanceof Date?x.date.toISOString():String(x.date),o:n(x.open),h:n(x.high),l:n(x.low),c:n(x.close),v:n(x.volume)})).filter(x=>x.c!=null&&x.h!=null&&x.l!=null&&x.v!=null);if(rows.length<220)throw Error('INSUFFICIENT_PRICE_HISTORY');return rows}
async function intraday(symbol){try{let raw=await yf.chart(norm(symbol),{period1:new Date(Date.now()-28*86400000),period2:new Date(),interval:'1h',events:'div,splits',return:'object'}),q=Array.isArray(raw?.quotes)?raw.quotes:[];return q.map(x=>({date:x.date instanceof Date?x.date.toISOString():String(x.date),o:n(x.open),h:n(x.high),l:n(x.low),c:n(x.close),v:n(x.volume)})).filter(x=>x.c!=null&&x.h!=null&&x.l!=null&&x.v!=null)}catch{return[]}}
function weekly(rows){const weeks=[];let key='',cur=null;for(const r of rows){const d=new Date(r.date),k=`${d.getUTCFullYear()}-${Math.floor((Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())-Date.UTC(d.getUTCFullYear(),0,1))/604800000)}`;if(k!==key){if(cur)weeks.push(cur);key=k;cur={o:r.o,h:r.h,l:r.l,c:r.c,v:r.v}}else{cur.h=Math.max(cur.h,r.h);cur.l=Math.min(cur.l,r.l);cur.c=r.c;cur.v+=r.v}}if(cur)weeks.push(cur);return weeks}
function candles(r){let x=r.at(-1),p=r.at(-2);if(!x||!p)return{};let body=Math.abs(x.c-x.o),range=x.h-x.l||1,upper=x.h-Math.max(x.o,x.c),lower=Math.min(x.o,x.c)-x.l;return{bullishEngulfing:x.c>x.o&&p.c<p.o&&x.c>=p.o&&x.o<=p.c,bearishEngulfing:x.c<x.o&&p.c>p.o&&x.o>=p.c&&x.c<=p.o,hammer:lower>=body*2&&upper<=body,shootingStar:upper>=body*2&&lower<=body,insideBar:x.h<=p.h&&x.l>=p.l,bodyPct:body/range*100}}
function technical(r){let c=r.map(x=>x.c),p=c.at(-1),e20=ema(c,20),e50=ema(c,50),e100=ema(c,100),e200=ema(c,200),a=atr(r),rs=rsi(c),m=macd(c),bb=bollinger(c),sk=stoch(r),adxv=adx(r),avgV=sma(r.map(x=>x.v),20),rv=avgV?r.at(-1).v/avgV:null,weeklyRows=weekly(r),wc=weeklyRows.map(x=>x.c),we20=ema(wc,20),trend=p>e20&&e20>e50&&e50>e200?'STRONG_UPTREND':p>e50&&e50>e200?'UPTREND':p<e50&&e50<e200?'DOWNTREND':'MIXED',mom5=pct(p,c.at(-6)),mom20=pct(p,c.at(-21)),hi20=Math.max(...r.slice(-20).map(x=>x.h)),lo20=Math.min(...r.slice(-20).map(x=>x.l)),hi55=Math.max(...r.slice(-55).map(x=>x.h)),lo55=Math.min(...r.slice(-55).map(x=>x.l)),hi252=Math.max(...r.slice(-252).map(x=>x.h)),lo252=Math.min(...r.slice(-252).map(x=>x.l)),bbState=bb?(bb.percentB>1?'ABOVE_BAND':bb.percentB<0?'BELOW_BAND':bb.width<6?'SQUEEZE':'INSIDE'):null,volTrend=r.at(-1).v>(sma(r.map(x=>x.v),5)||0)?'RISING':'FALLING';let bull=50;if(trend==='STRONG_UPTREND')bull+=16;else if(trend==='UPTREND')bull+=9;else if(trend==='DOWNTREND')bull-=18;if(we20!=null&&wc.at(-1)>we20)bull+=5;else if(we20!=null)bull-=5;if(p>e20)bull+=6;else bull-=6;if(rs!=null){if(rs>=55&&rs<=72)bull+=7;else if(rs>78)bull-=6;else if(rs<35)bull-=8}if(m?.histogram!=null)bull+=m.histogram>0?7:-7;if(adxv!=null&&adxv>=25)bull+=5;if(rv!=null&&rv>=1.25)bull+=6;if(mom5>3)bull+=4;else if(mom5<-3)bull-=4;if(candles(r).bullishEngulfing)bull+=5;if(candles(r).bearishEngulfing)bull-=5;if(bbState==='SQUEEZE')bull+=1;return{last:p,e20,e50,e100,e200,weeklyEMA20:we20,weeklyClose:wc.at(-1),atr:a,atrPct:a&&p?a/p*100:null,rsi:rs,macd:m,bollinger:bb,stochastic:sk,adx:adxv,relativeVolume:rv,volumeTrend:volTrend,trend,momentum5d:mom5,momentum20d:mom20,high20:hi20,low20:lo20,high55:hi55,low55:lo55,high252:hi252,low252:lo252,drawdown:pct(p,hi252),distance20High:pct(p,hi20),distance55High:pct(p,hi55),distance52Low:pct(p,lo252),bollingerState:bbState,candles:candles(r),bullScore:clamp(bull),bearScore:clamp(100-bull),obv:obv(r)}}
function setup(t,i=[]){let p=t.last,a=t.atr||p*.02,bt=t.high20*1.002,st=t.low20*.998,bs=Math.min(t.e20-a*.8,p-a*1.4),ss=Math.max(t.e20+a*.8,p+a*1.4),b1=p+2*a,b2=p+3.5*a,s1=p-2*a,s2=p-3.5*a,brr=(b1-p)/(p-bs),srr=(p-s1)/(ss-p),breakout=p>t.high20*.995&&t.relativeVolume>=1.1,breakdown=p<t.low20*1.005&&t.relativeVolume>=1.1,action='WAIT';if(t.bullScore>=75&&t.trend!=='DOWNTREND'&&t.rsi<76&&t.relativeVolume>=.9&&brr>=1.5&&(!breakout||t.relativeVolume>=1.1))action='BUY_READY';else if(t.bearScore>=75&&t.trend==='DOWNTREND'&&t.rsi>24&&t.relativeVolume>=.9&&srr>=1.5)action='SELL_READY';else if(t.trend==='UPTREND'&&t.rsi<48)action='BUY_ON_PULLBACK';else if(t.trend==='DOWNTREND'&&t.rsi>52)action='SELL_ON_RALLY';let mtf=i.length?technical(i):null;if(mtf&&action.includes('READY')){if(action==='BUY_READY'&&mtf.bullScore<55)action='WAIT_MTF_CONFLICT';if(action==='SELL_READY'&&mtf.bearScore<55)action='WAIT_MTF_CONFLICT'}return{action,readiness:Math.round(action.startsWith('BUY')?t.bullScore:action.startsWith('SELL')?t.bearScore:Math.max(t.bullScore,t.bearScore)),breakout,breakdown,buy:{trigger:bt,stop:bs,target1:b1,target2:b2,riskReward:+brr.toFixed(2)},sell:{trigger:st,stop:ss,target1:s1,target2:s2,riskReward:+srr.toFixed(2)}}}
function evidence(t){let e=[];if(t.trend.includes('UPTREND'))e.push('Daily trend structure bullish');if(t.trend==='DOWNTREND')e.push('Daily trend structure bearish');if(t.weeklyClose>t.weeklyEMA20)e.push('Weekly price above EMA20');else e.push('Weekly trend not confirmed');if(t.rsi>=55&&t.rsi<=72)e.push('RSI momentum zone');if(t.rsi>78)e.push('RSI overheated risk');if(t.rsi<40)e.push('RSI weakness');if(t.macd?.histogram>0)e.push('MACD histogram positive');if(t.macd?.histogram<0)e.push('MACD histogram negative');if(t.adx>=25)e.push('ADX confirms trend strength');if(t.relativeVolume>=1.25)e.push('Volume expansion');if(t.momentum5d>3)e.push('5D momentum positive');if(t.momentum5d<-3)e.push('5D momentum negative');if(t.bollingerState==='SQUEEZE')e.push('Bollinger squeeze: expansion watch');if(t.candles?.bullishEngulfing)e.push('Bullish engulfing candle');if(t.candles?.bearishEngulfing)e.push('Bearish engulfing candle');if(t.candles?.hammer)e.push('Hammer/rejection candle');if(t.candles?.shootingStar)e.push('Shooting-star rejection');return e}
export async function scanSymbols(symbols=DEFAULT_UNIVERSE){let u=[...new Set(symbols.map(norm))].slice(0,100),out=[],errors=[],i=0;async function w(){while(i<u.length){let s=u[i++];try{let r=await daily(s),t=technical(r);out.push({symbol:s.replace(/\.NS$|\.BO$/,''),yahooSymbol:s,price:t.last,asOf:r.at(-1)?.date,technical:t,setup:null,evidence:evidence(t),dataStatus:'VERIFIED_MARKET_DATA',historyDays:r.length})}catch(e){errors.push({symbol:s,error:e?.message||'UNAVAILABLE'})}}}await Promise.all(Array.from({length:5},w));out.sort((a,b)=>b.technical.bullScore-b.technical.bullScore);const deep=out.slice(0,15);let j=0;async function dw(){while(j<deep.length){let item=deep[j++];try{let ir=await intraday(item.yahooSymbol);item.intraday={bars:ir.length,technical:ir.length>=50?technical(ir):null};item.setup=setup(item.technical,ir)}catch{item.setup=setup(item.technical)}}}await Promise.all(Array.from({length:3},dw));out.sort((a,b)=>(b.setup?.readiness??b.technical.bullScore)-(a.setup?.readiness??a.technical.bullScore));return{generatedAt:new Date().toISOString(),universeRequested:u.length,scanned:out.length,errors,results:out,policy:{fakeDataAllowed:false,missingDataAction:'EXCLUDE_FROM_READY_LIST',decisionBasis:'verified market history + deterministic indicators; no invented values'},indicatorSet:['EMA20','EMA50','EMA100','EMA200','Weekly EMA20','RSI14','MACD12/26/9','ATR14','ADX14','Bollinger20/2','Stochastic14','RelativeVolume20','OBV','PriceAction','CandlestickPatterns','Breakout/Breakdown','MultiTimeframe1H']}}
