import YahooFinance from 'yahoo-finance2';
const yf=new YahooFinance();
const n=v=>typeof v==='number'&&Number.isFinite(v)?v:v&&Number.isFinite(v.raw)?v.raw:null;
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,Number.isFinite(v)?v:a));
const pct=(a,b)=>a!=null&&b?((a/b)-1)*100:null;
const avg=(a,p)=>a.length>=p?a.slice(-p).reduce((s,x)=>s+x,0)/p:null;
const ema=(a,p)=>{if(a.length<p)return null;let e=avg(a.slice(0,p),p),k=2/(p+1);for(let i=p;i<a.length;i++)e=a[i]*k+e*(1-k);return e};
function rsi(c,p=14){if(c.length<=p)return null;let g=0,l=0;for(let i=1;i<=p;i++){let d=c[i]-c[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=p;l/=p;for(let i=p+1;i<c.length;i++){let d=c[i]-c[i-1];g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p}return l===0?100:100-100/(1+g/l)}
function atr(r,p=14){if(r.length<=p)return null;let tr=[];for(let i=1;i<r.length;i++){let x=r[i],q=r[i-1];tr.push(Math.max(x.h-x.l,Math.abs(x.h-q.c),Math.abs(x.l-q.c)))}let a=avg(tr.slice(0,p),p);for(let i=p;i<tr.length;i++)a=(a*(p-1)+tr[i])/p;return a}
function macd(c){if(c.length<35)return null;let s=[];for(let i=26;i<=c.length;i++){let z=c.slice(0,i);s.push(ema(z,12)-ema(z,26))}let line=s.at(-1),signal=ema(s,9);return{line,signal,histogram:signal==null?null:line-signal}}
function boll(c,p=20,k=2){if(c.length<p)return null;let m=avg(c,p),sd=Math.sqrt(c.slice(-p).reduce((s,x)=>s+(x-m)**2,0)/p),u=m+k*sd,l=m-k*sd;return{middle:m,upper:u,lower:l,width:m?(u-l)/m*100:null,percentB:u===l?null:(c.at(-1)-l)/(u-l)}}
function stoch(r,p=14){if(r.length<p)return null;let x=r.slice(-p),hi=Math.max(...x.map(z=>z.h)),lo=Math.min(...x.map(z=>z.l));return{k:hi===lo?50:(r.at(-1).c-lo)/(hi-lo)*100}}
function adx(r,p=14){if(r.length<2*p+2)return null;let tr=[],pd=[],md=[];for(let i=1;i<r.length;i++){let x=r[i],q=r[i-1],up=x.h-q.h,dn=q.l-x.l;tr.push(Math.max(x.h-x.l,Math.abs(x.h-q.c),Math.abs(x.l-q.c)));pd.push(up>dn&&up>0?up:0);md.push(dn>up&&dn>0?dn:0)}let t=avg(tr,p),pp=avg(pd,p),mm=avg(md,p),dx=[];for(let i=p;i<tr.length;i++){t=t-t/p+tr[i];pp=pp-pp/p+pd[i];mm=mm-mm/p+md[i];let P=t?100*pp/t:0,M=t?100*mm/t:0;dx.push(P+M?100*Math.abs(P-M)/(P+M):0)}return dx.length>=p?avg(dx.slice(-p),p):null}
function obv(r){let v=0;for(let i=1;i<r.length;i++)v+=r[i].c>r[i-1].c?r[i].v:r[i].c<r[i-1].c?-r[i].v:0;return v}
function candles(r){let x=r.at(-1),q=r.at(-2),q3=r.at(-3);if(!x||!q)return{};let body=Math.abs(x.c-x.o),range=x.h-x.l||1,u=x.h-Math.max(x.o,x.c),l=Math.min(x.o,x.c)-x.l;return{bullishEngulfing:x.c>x.o&&q.c<q.o&&x.c>=q.o&&x.o<=q.c,bearishEngulfing:x.c<x.o&&q.c>q.o&&x.o>=q.c&&x.c<=q.o,hammer:l>=body*2&&u<=body,shootingStar:u>=body*2&&l<=body,insideBar:x.h<=q.h&&x.l>=q.l,bodyPct:body/range*100,gapPct:pct(x.o,q.c),threeBarMomentum:q3?pct(x.c,q3.c):null}}
const norm=s=>{s=String(s||'').trim().toUpperCase();return s.endsWith('.NS')||s.endsWith('.BO')?s:`${s}.NS`};
export const DEFAULT_UNIVERSE=['RELIANCE','TCS','HDFCBANK','ICICIBANK','INFY','BHARTIARTL','SBIN','LICI','ITC','HINDUNILVR','LT','BAJFINANCE','HCLTECH','MARUTI','M&M','KOTAKBANK','SUNPHARMA','AXISBANK','ULTRACEMCO','TITAN','ADANIENT','ADANIPORTS','NTPC','ONGC','POWERGRID','TATASTEEL','JSWSTEEL','NESTLEIND','ASIANPAINT','WIPRO','TECHM','TATAMOTORS','BAJAJFINSV','COALINDIA','HINDALCO','TRENT','EICHERMOT','GRASIM','CIPLA','DRREDDY','DIVISLAB','APOLLOHOSP','SBILIFE','HDFCLIFE','BAJAJ-AUTO','HEROMOTOCO','TATACONSUM','BEL','HAL','INDUSINDBK'];
async function chart(symbol,interval='1d',days=900){let raw=await yf.chart(norm(symbol),{period1:new Date(Date.now()-days*86400000),period2:new Date(),interval,events:'div,splits',return:'object'});let q=Array.isArray(raw?.quotes)?raw.quotes:[];return q.map(x=>({date:x.date instanceof Date?x.date.toISOString():String(x.date),o:n(x.open),h:n(x.high),l:n(x.low),c:n(x.close),v:n(x.volume)})).filter(x=>x.c!=null&&x.h!=null&&x.l!=null&&x.v!=null&&x.o!=null)}
function weekly(r){let w=[];for(const x of r){let d=new Date(x.date),key=`${d.getUTCFullYear()}-${Math.floor((Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())-Date.UTC(d.getUTCFullYear(),0,1))/604800000)}`,z=w.at(-1);if(!z||z.key!==key)w.push({key,o:x.o,h:x.h,l:x.l,c:x.c,v:x.v});else{z.h=Math.max(z.h,x.h);z.l=Math.min(z.l,x.l);z.c=x.c;z.v+=x.v}}return w}
function technical(r){let c=r.map(x=>x.c),p=c.at(-1),e20=ema(c,20),e50=ema(c,50),e100=ema(c,100),e200=ema(c,200),a=atr(r),rs=rsi(c),m=macd(c),bb=boll(c),sk=stoch(r),ax=adx(r),vol=r.map(x=>x.v),av=avg(vol,20),rv=av?p/ p*r.at(-1).v/av:null,w=weekly(r),wc=w.map(x=>x.c),we20=ema(wc,20),cp=candles(r),ob=obv(r),ob20=obv(r.slice(0,Math.max(1,r.length-20))),hi20=Math.max(...r.slice(-20).map(x=>x.h)),lo20=Math.min(...r.slice(-20).map(x=>x.l)),hi55=Math.max(...r.slice(-Math.min(55,r.length)).map(x=>x.h)),lo55=Math.min(...r.slice(-Math.min(55,r.length)).map(x=>x.l)),hi252=Math.max(...r.slice(-Math.min(252,r.length)).map(x=>x.h)),lo252=Math.min(...r.slice(-Math.min(252,r.length)).map(x=>x.l));
let trend=e200?(p>e20&&e20>e50&&e50>e100&&e100>e200?'STRONG_UPTREND':p>e50&&e50>e200?'UPTREND':p<e50&&e50<e200?'DOWNTREND':'MIXED'):e50?(p>e20&&e20>e50?'UPTREND':p<e50?'DOWNTREND':'MIXED'):'MIXED';
let bull=50; if(trend==='STRONG_UPTREND')bull+=16;else if(trend==='UPTREND')bull+=9;else if(trend==='DOWNTREND')bull-=18;if(we20!=null)bull+=wc.at(-1)>we20?6:-6;if(e20!=null)bull+=p>e20?6:-6;if(rs!=null){if(rs>=55&&rs<=72)bull+=7;else if(rs>78)bull-=6;else if(rs<35)bull-=8}if(m?.histogram!=null)bull+=m.histogram>0?7:-7;if(ax!=null&&ax>=25)bull+=5;if(rv!=null&&rv>=1.25)bull+=6;let m5=pct(p,c.at(-6)),m20=pct(p,c.at(-21));if(m5>3)bull+=4;else if(m5<-3)bull-=4;if(cp.bullishEngulfing||cp.hammer)bull+=4;if(cp.bearishEngulfing||cp.shootingStar)bull-=4;let range20=hi20-lo20,position=range20?pct(p,lo20)/((hi20/lo20)-1)/100:null;let historyQuality=clamp(r.length/252*100);
return{last:p,e20,e50,e100,e200,weeklyEMA20:we20,weeklyClose:wc.at(-1),atr:a,atrPct:a&&p?a/p*100:null,rsi:rs,macd:m,bollinger:bb,stochastic:sk,adx:ax,relativeVolume:rv,obv:ob,obvTrend:ob>ob20?'RISING':'FALLING',trend,momentum5d:m5,momentum20d:m20,high20:hi20,low20:lo20,high55:hi55,low55:lo55,high252:hi252,low252:lo252,drawdown52w:pct(p,hi252),distance20High:pct(p,hi20),distance55High:pct(p,hi55),distance52Low:pct(p,lo252),range20,rangePosition:position,candles:cp,bullScore:Math.round(clamp(bull)),bearScore:Math.round(clamp(100-bull)),historyBars:r.length,historyQuality:Math.round(historyQuality),ema200Available:Boolean(e200)}}
function setup(t,i){let p=t.last,a=t.atr||p*.02,vol=t.relativeVolume??0,bs=Math.min(t.e20-a*.8,p-a*1.4),ss=Math.max(t.e20+a*.8,p+a*1.4),buyTrigger=Math.max(t.high20*1.001,p+a*.15),sellTrigger=Math.min(t.low20*.999,p-a*.15),b1=buyTrigger+1.8*a,b2=buyTrigger+3*a,s1=sellTrigger-1.8*a,s2=sellTrigger-3*a,brr=(b1-buyTrigger)/(buyTrigger-bs),srr=(sellTrigger-s1)/(ss-sellTrigger),mtf=i&&i.length>=50?technical(i):null;
let long=t.bullScore>=70&&t.trend!=='DOWNTREND'&&t.rsi!=null&&t.rsi<76&&vol>=.9&&brr>=1.5&&t.historyBars>=120;let short=t.bearScore>=70&&t.trend==='DOWNTREND'&&t.rsi!=null&&t.rsi>24&&vol>=.9&&srr>=1.5&&t.historyBars>=120;let action=long?'BUY_READY':short?'SELL_READY':t.trend==='UPTREND'&&t.rsi<50?'BUY_ON_PULLBACK':t.trend==='DOWNTREND'&&t.rsi>50?'SELL_ON_RALLY':'WAIT';if(mtf&&action==='BUY_READY'&&mtf.bullScore<52)action='WAIT_MTF_CONFLICT';if(mtf&&action==='SELL_READY'&&mtf.bearScore<52)action='WAIT_MTF_CONFLICT';
let confidence=Math.round(clamp((Math.max(t.bullScore,t.bearScore)*.45)+(Math.min(100,t.historyQuality)*.2)+(Math.min(100,(vol/1.5)*100)*.15)+((mtf?Math.max(mtf.bullScore,mtf.bearScore):50)*.2)));return{action,readiness:Math.max(t.bullScore,t.bearScore),confidence,tradeHorizon:action.includes('READY')?'NEXT_SESSION':action.includes('PULLBACK')||action.includes('RALLY')?'SWING_WATCH':'NO_SETUP',buy:{trigger:+buyTrigger.toFixed(2),stop:+bs.toFixed(2),target1:+b1.toFixed(2),target2:+b2.toFixed(2),riskReward:+brr.toFixed(2)},sell:{trigger:+sellTrigger.toFixed(2),stop:+ss.toFixed(2),target1:+s1.toFixed(2),target2:+s2.toFixed(2),riskReward:+srr.toFixed(2)},gates:{historyVerified:t.historyBars>=120,volumeConfirmed:vol>=.9,riskRewardConfirmed:Math.max(brr,srr)>=1.5,trendConfirmed:t.trend!=='MIXED',multiTimeframeChecked:Boolean(mtf)}}}
function evidence(t){let e=[];if(t.trend.includes('UPTREND'))e.push('Daily trend structure bullish');if(t.trend==='DOWNTREND')e.push('Daily trend structure bearish');if(t.weeklyClose>t.weeklyEMA20)e.push('Weekly EMA20 confirmation');else if(t.weeklyEMA20)e.push('Weekly trend not confirmed');if(t.rsi>=55&&t.rsi<=72)e.push('RSI momentum zone');if(t.rsi<40)e.push('RSI weakness');if(t.macd?.histogram>0)e.push('MACD histogram positive');if(t.macd?.histogram<0)e.push('MACD histogram negative');if(t.adx>=25)e.push('ADX trend strength');if(t.relativeVolume>=1.25)e.push('Volume expansion');if(t.obvTrend==='RISING')e.push('OBV accumulation');if(t.distance20High>=-2)e.push('Near 20D breakout zone');if(t.candles?.bullishEngulfing)e.push('Bullish engulfing');if(t.candles?.bearishEngulfing)e.push('Bearish engulfing');if(t.candles?.hammer)e.push('Hammer/rejection');if(t.candles?.shootingStar)e.push('Shooting-star rejection');return e}
export async function scanSymbols(symbols=DEFAULT_UNIVERSE){let u=[...new Set(symbols.map(norm))].slice(0,100),out=[],errors=[],i=0;async function worker(){while(i<u.length){let s=u[i++];try{let r=await chart(s,'1d',900);if(r.length<60)throw Error('INSUFFICIENT_VERIFIED_PRICE_HISTORY');let t=technical(r);out.push({symbol:s.replace(/\.NS$|\.BO$/,''),yahooSymbol:s,price:t.last,asOf:r.at(-1)?.date,technical:t,setup:null,evidence:evidence(t),dataStatus:'VERIFIED_MARKET_DATA',historyDays:r.length})}catch(e){errors.push({symbol:s,error:e?.message||'UNAVAILABLE'})}}}await Promise.all(Array.from({length:6},worker));out.sort((a,b)=>Math.max(b.technical.bullScore,b.technical.bearScore)-Math.max(a.technical.bullScore,a.technical.bearScore));const deep=out.slice(0,20);let j=0;async function deepWorker(){while(j<deep.length){let x=deep[j++];try{let ir=await chart(x.yahooSymbol,'1h',45);x.intraday={bars:ir.length,technical:ir.length>=50?technical(ir):null};x.setup=setup(x.technical,ir)}catch{x.setup=setup(x.technical,[])}}}await Promise.all(Array.from({length:4},deepWorker));out.sort((a,b)=>(b.setup?.confidence??0)-(a.setup?.confidence??0));let ready=out.filter(x=>['BUY_READY','SELL_READY'].includes(x.setup?.action));return{generatedAt:new Date().toISOString(),universeRequested:u.length,scanned:out.length,readyCount:ready.length,readyList:ready,errors,results:out,policy:{fakeDataAllowed:false,missingDataAction:'EXCLUDE_FROM_READY_LIST',decisionBasis:'verified OHLCV + deterministic multi-indicator scoring + risk/reward + optional 1H confirmation; no invented values'},indicatorSet:['EMA20','EMA50','EMA100','EMA200','Weekly EMA20','RSI14','MACD12/26/9','ATR14','ADX14','Bollinger20/2','Stochastic14','RelativeVolume20','OBV','20D/55D/52W structure','Gap/Range/Candle price action','Breakout/Breakdown','MultiTimeframe1H','Risk/Reward','Next-session readiness']}}
