import YahooFinance from 'yahoo-finance2';
const yf=new YahooFinance();
const n=v=>typeof v==='number'&&Number.isFinite(v)?v:v&&Number.isFinite(v.raw)?v.raw:null;
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,Number.isFinite(v)?v:a));
const pct=(a,b)=>a!=null&&b?((a/b)-1)*100:null;
const sma=(a,p)=>a.length>=p?a.slice(-p).reduce((s,x)=>s+x,0)/p:null;
const ema=(a,p)=>{if(a.length<p)return null;let e=sma(a.slice(0,p),p),k=2/(p+1);for(let i=p;i<a.length;i++)e=a[i]*k+e*(1-k);return e};
function rsi(a,p=14){if(a.length<=p)return null;let g=0,l=0;for(let i=1;i<=p;i++){let d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=p;l/=p;for(let i=p+1;i<a.length;i++){let d=a[i]-a[i-1];g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p}return l===0?100:100-100/(1+g/l)}
function atr(r,p=14){if(r.length<=p)return null;let tr=[];for(let i=1;i<r.length;i++){let x=r[i],q=r[i-1];tr.push(Math.max(x.h-x.l,Math.abs(x.h-q.c),Math.abs(x.l-q.c)))}let a=sma(tr.slice(0,p),p);for(let i=p;i<tr.length;i++)a=(a*(p-1)+tr[i])/p;return a}
function macd(c){if(c.length<35)return null;let s=[];for(let i=26;i<=c.length;i++){let z=c.slice(0,i);s.push(ema(z,12)-ema(z,26))}let line=s.at(-1),sig=ema(s,9);return{line,signal:sig,histogram:sig==null?null:line-sig}}
function boll(c,p=20,k=2){if(c.length<p)return null;let m=sma(c,p),sd=Math.sqrt(c.slice(-p).reduce((s,x)=>s+(x-m)**2,0)/p),u=m+k*sd,l=m-k*sd;return{middle:m,upper:u,lower:l,width:m?(u-l)/m*100:null,percentB:u===l?null:(c.at(-1)-l)/(u-l)}}
function stoch(r,p=14){if(r.length<p)return null;let x=r.slice(-p),hi=Math.max(...x.map(z=>z.h)),lo=Math.min(...x.map(z=>z.l));return{k:hi===lo?50:(r.at(-1).c-lo)/(hi-lo)*100}}
function adx(r,p=14){if(r.length<2*p+2)return null;let tr=[],pd=[],md=[];for(let i=1;i<r.length;i++){let x=r[i],q=r[i-1],up=x.h-q.h,dn=q.l-x.l;tr.push(Math.max(x.h-x.l,Math.abs(x.h-q.c),Math.abs(x.l-q.c)));pd.push(up>dn&&up>0?up:0);md.push(dn>up&&dn>0?dn:0)}let t=sma(tr,p),pp=sma(pd,p),mm=sma(md,p),dx=[];for(let i=p;i<tr.length;i++){t=t-t/p+tr[i];pp=pp-pp/p+pd[i];mm=mm-mm/p+md[i];let P=t?100*pp/t:0,M=t?100*mm/t:0;dx.push(P+M?100*Math.abs(P-M)/(P+M):0)}return dx.length>=p?sma(dx.slice(-p),p):null}
function obv(r){let v=0;for(let i=1;i<r.length;i++)v+=r[i].c>r[i-1].c?r[i].v:r[i].c<r[i-1].c?-r[i].v:0;return v}
function candles(r){let x=r.at(-1),q=r.at(-2);if(!x||!q)return{};let body=Math.abs(x.c-x.o),range=x.h-x.l||1,u=x.h-Math.max(x.o,x.c),l=Math.min(x.o,x.c)-x.l;return{bullishEngulfing:x.c>x.o&&q.c<q.o&&x.c>=q.o&&x.o<=q.c,bearishEngulfing:x.c<x.o&&q.c>q.o&&x.o>=q.c&&x.c<=q.o,hammer:l>=body*2&&u<=body,shootingStar:u>=body*2&&l<=body,insideBar:x.h<=q.h&&x.l>=q.l}}
const norm=s=>{s=String(s||'').trim().toUpperCase();return s.endsWith('.NS')||s.endsWith('.BO')?s:`${s}.NS`};
export const DEFAULT_UNIVERSE=['RELIANCE','TCS','HDFCBANK','ICICIBANK','INFY','BHARTIARTL','SBIN','LICI','ITC','HINDUNILVR','LT','BAJFINANCE','HCLTECH','MARUTI','M&M','KOTAKBANK','SUNPHARMA','AXISBANK','ULTRACEMCO','TITAN','ADANIENT','ADANIPORTS','NTPC','ONGC','POWERGRID','TATASTEEL','JSWSTEEL','NESTLEIND','ASIANPAINT','WIPRO','TECHM','TATAMOTORS','BAJAJFINSV','COALINDIA','HINDALCO','TRENT','EICHERMOT','GRASIM','CIPLA','DRREDDY','DIVISLAB','APOLLOHOSP','SBILIFE','HDFCLIFE','BAJAJ-AUTO','HEROMOTOCO','TATACONSUM','BEL','HAL','INDUSINDBK'];
async function chart(symbol,interval='1d',days=900){let raw=await yf.chart(norm(symbol),{period1:new Date(Date.now()-days*86400000),period2:new Date(),interval,events:'div,splits',return:'object'});let q=Array.isArray(raw?.quotes)?raw.quotes:[];return q.map(x=>({date:x.date instanceof Date?x.date.toISOString():String(x.date),o:n(x.open),h:n(x.high),l:n(x.low),c:n(x.close),v:n(x.volume)})).filter(x=>x.c!=null&&x.h!=null&&x.l!=null&&x.v!=null)}
function weekly(r){let w=[];for(const x of r){let d=new Date(x.date),key=`${d.getUTCFullYear()}-${Math.floor((Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())-Date.UTC(d.getUTCFullYear(),0,1))/604800000)}`;let z=w.at(-1);if(!z||z.key!==key)w.push({key,o:x.o,h:x.h,l:x.l,c:x.c,v:x.v});else{z.h=Math.max(z.h,x.h);z.l=Math.min(z.l,x.l);z.c=x.c;z.v+=x.v}}return w}
function technical(r){let c=r.map(x=>x.c),p=c.at(-1),e20=ema(c,20),e50=ema(c,50),e100=ema(c,100),e200=ema(c,200),a=atr(r),rs=rsi(c),m=macd(c),bb=boll(c),sk=stoch(r),ax=adx(r),av=sma(r.map(x=>x.v),20),rv=av?r.at(-1).v/av:null,w=weekly(r),wc=w.map(x=>x.c),we20=ema(wc,20),trend=e200&&e100?(p>e20&&e20>e50&&e50>e100&&e100>e200?'STRONG_UPTREND':p>e50&&e50>e200?'UPTREND':p<e50&&e50<e200?'DOWNTREND':'MIXED'):e50?(p>e20&&e20>e50?'UPTREND':p<e50?'DOWNTREND':'MIXED'):'MIXED',mom5=pct(p,c.at(-6)),mom20=pct(p,c.at(-21)),hi20=Math.max(...r.slice(-20).map(x=>x.h)),lo20=Math.min(...r.slice(-20).map(x=>x.l)),hi55=Math.max(...r.slice(-55).map(x=>x.h)),lo55=Math.min(...r.slice(-55).map(x=>x.l)),hi252=Math.max(...r.slice(-Math.min(252,r.length)).map(x=>x.h)),lo252=Math.min(...r.slice(-Math.min(252,r.length)).map(x=>x.l)),ob=obv(r),obOld=obv(r.slice(0,-Math.min(20,r.length-1))),cp=candles(r);let bull=50;if(trend==='STRONG_UPTREND')bull+=16;else if(trend==='UPTREND')bull+=9;else if(trend==='DOWNTREND')bull-=18;if(we20!=null)bull+=wc.at(-1)>we20?5:-5;if(e20!=null)bull+=p>e20?6:-6;if(rs!=null){if(rs>=55&&rs<=72)bull+=7;else if(rs>78)bull-=6;else if(rs<35)bull-=8}if(m?.histogram!=null)bull+=m.histogram>0?7:-7;if(ax!=null&&ax>=25)bull+=5;if(rv!=null&&rv>=1.25)bull+=6;if(mom5>3)bull+=4;else if(mom5<-3)bull-=4;if(cp.bullishEngulfing||cp.hammer)bull+=4;if(cp.bearishEngulfing||cp.shootingStar)bull-=4;const historyQuality=clamp((r.length/252)*100);return{last:p,e20,e50,e100,e200,weeklyEMA20:we20,weeklyClose:wc.at(-1),atr:a,atrPct:a&&p?a/p*100:null,rsi:rs,macd:m,bollinger:bb,stochastic:sk,adx:ax,relativeVolume:rv,obvTrend:ob>obOld?'RISING':'FALLING',trend,momentum5d:mom5,momentum20d:mom20,high20:hi20,low20:lo20,high55:hi55,low55:lo55,high252:hi252,low252:lo252,drawdown52w:pct(p,hi252),distance20High:pct(p,hi20),distance55High:pct(p,hi55),candles:cp,bullScore:Math.round(clamp(bull)),bearScore:Math.round(clamp(100-bull)),historyBars:r.length,historyQuality:Math.round(historyQuality),ema200Available:e200!=null}}
function setup(t,i){let p=t.last,a=t.atr||p*.02,bs=Math.min(t.e20-a*.8,p-a*1.4),ss=Math.max(t.e20+a*.8,p+a*1.4),b1=p+2*a,b2=p+3.5*a,s1=p-2*a,s2=p-3.5*a,brr=(b1-p)/(p-bs),srr=(p-s1)/(ss-p),mtf=i&&i.length>=50?technical(i):null,action='WAIT';const long=t.bullScore>=75&&t.trend!=='DOWNTREND'&&t.rsi<76&&t.relativeVolume>=.9&&brr>=1.5&&t.historyBars>=120;const short=t.bearScore>=75&&t.trend==='DOWNTREND'&&t.rsi>24&&t.relativeVolume>=.9&&srr>=1.5&&t.historyBars>=120;if(long)action='BUY_READY';else if(short)action='SELL_READY';else if(t.trend==='UPTREND'&&t.rsi<48)action='BUY_ON_PULLBACK';else if(t.trend==='DOWNTREND'&&t.rsi>52)action='SELL_ON_RALLY';if(mtf&&action==='BUY_READY'&&mtf.bullScore<55)action='WAIT_MTF_CONFLICT';if(mtf&&action==='SELL_READY'&&mtf.bearScore<55)action='WAIT_MTF_CONFLICT';return{action,readiness:Math.max(t.bullScore,t.bearScore),buy:{trigger:t.high20*1.002,stop:bs,target1:b1,target2:b2,riskReward:+brr.toFixed(2)},sell:{trigger:t.low20*.998,stop:ss,target1:s1,target2:s2,riskReward:+srr.toFixed(2)},gates:{historyVerified:t.historyBars>=120,volumeConfirmed:t.relativeVolume>=.9,riskRewardConfirmed:Math.max(brr,srr)>=1.5,multiTimeframeChecked:Boolean(mtf)}}}
function evidence(t){let e=[];if(t.trend.includes('UPTREND'))e.push('Daily trend bullish');if(t.trend==='DOWNTREND')e.push('Daily trend bearish');if(t.weeklyClose>t.weeklyEMA20)e.push('Weekly EMA20 confirmation');if(t.rsi>=55&&t.rsi<=72)e.push('RSI momentum');if(t.macd?.histogram>0)e.push('MACD positive');if(t.adx>=25)e.push('ADX trend strength');if(t.relativeVolume>=1.25)e.push('Volume expansion');if(t.obvTrend==='RISING')e.push('OBV rising');if(t.candles?.bullishEngulfing)e.push('Bullish engulfing');if(t.candles?.bearishEngulfing)e.push('Bearish engulfing');if(t.candles?.hammer)e.push('Hammer');if(t.candles?.shootingStar)e.push('Shooting star');return e}
export async function scanSymbols(symbols=DEFAULT_UNIVERSE){let u=[...new Set(symbols.map(norm))].slice(0,100),out=[],errors=[],i=0;async function w(){while(i<u.length){let s=u[i++];try{let r=await chart(s,'1d',900);if(r.length<120)throw Error('INSUFFICIENT_VERIFIED_PRICE_HISTORY');let t=technical(r);out.push({symbol:s.replace(/\.NS$|\.BO$/,''),yahooSymbol:s,price:t.last,asOf:r.at(-1)?.date,technical:t,setup:null,evidence:evidence(t),dataStatus:'VERIFIED_MARKET_DATA',historyDays:r.length})}catch(e){errors.push({symbol:s,error:e?.message||'UNAVAILABLE'})}}}await Promise.all(Array.from({length:5},w));out.sort((a,b)=>b.technical.bullScore-a.technical.bullScore);const deep=out.slice(0,15);let j=0;async function dw(){while(j<deep.length){let x=deep[j++];try{let ir=await chart(x.yahooSymbol,'1h',60);x.intraday={bars:ir.length,technical:ir.length>=50?technical(ir):null};x.setup=setup(x.technical,ir)}catch{x.setup=setup(x.technical,[])}}}await Promise.all(Array.from({length:3},dw));out.sort((a,b)=>(b.setup?.readiness??b.technical.bullScore)-(a.setup?.readiness??a.technical.bullScore));return{generatedAt:new Date().toISOString(),universeRequested:u.length,scanned:out.length,errors,results:out,policy:{fakeDataAllowed:false,missingDataAction:'EXCLUDE_FROM_READY_LIST',decisionBasis:'verified OHLCV only; no fallback or invented values'},indicatorSet:['EMA20','EMA50','EMA100','EMA200','Weekly EMA20','RSI14','MACD12/26/9','ATR14','ADX14','Bollinger20/2','Stochastic14','RelativeVolume20','OBV','PriceAction','CandlestickPatterns','Breakout/Breakdown','MultiTimeframe1H']}}
