const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
const clamp=(x,a=0,b=100)=>Math.max(a,Math.min(b,Number.isFinite(x)?x:a));
const sma=(a,p)=>a.length<p?null:a.slice(-p).reduce((s,x)=>s+x,0)/p;
const ema=(a,p)=>{if(a.length<p)return null;let e=a.slice(0,p).reduce((s,x)=>s+x,0)/p,k=2/(p+1);for(let i=p;i<a.length;i++)e=a[i]*k+e*(1-k);return e};
function rsi(a,p=14){if(a.length<=p)return null;let g=0,l=0;for(let i=1;i<=p;i++){const d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=p;l/=p;for(let i=p+1;i<a.length;i++){const d=a[i]-a[i-1];g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p}return l===0?100:100-100/(1+g/l)}
function macd(a){if(a.length<35)return {line:null,signal:null,histogram:null};const line=[];for(let i=0;i<a.length;i++){const e12=ema(a.slice(0,i+1),12),e26=ema(a.slice(0,i+1),26);if(e12!=null&&e26!=null)line.push(e12-e26)}const signal=ema(line,9);return {line:line.at(-1)??null,signal,histogram:line.at(-1)!=null&&signal!=null?line.at(-1)-signal:null};}
function atr(rows,p=14){if(rows.length<=p)return null;const tr=[];for(let i=1;i<rows.length;i++){const x=rows[i],q=rows[i-1];tr.push(Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close)))}let a=tr.slice(0,p).reduce((s,x)=>s+x,0)/p;for(let i=p;i<tr.length;i++)a=((a*(p-1))+tr[i])/p;return a}
function adx(rows,p=14){if(rows.length<2*p+2)return null;const trs=[],plus=[],minus=[];for(let i=1;i<rows.length;i++){const x=rows[i],q=rows[i-1];trs.push(Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close)));const up=x.high-q.high,down=q.low-x.low;plus.push(up>down&&up>0?up:0);minus.push(down>up&&down>0?down:0)}let tr=trs.slice(0,p).reduce((s,x)=>s+x,0),pdm=plus.slice(0,p).reduce((s,x)=>s+x,0),mdm=minus.slice(0,p).reduce((s,x)=>s+x,0),dx=[];for(let i=p;i<trs.length;i++){tr=tr-tr/p+trs[i];pdm=pdm-pdm/p+plus[i];mdm=mdm-mdm/p+minus[i];const pi=tr?100*pdm/tr:0,mi=tr?100*mdm/tr:0;dx.push(pi+mi?100*Math.abs(pi-mi)/(pi+mi):0)}return dx.length>=p?sma(dx.slice(-p),p):null}
function vwap(rows,p=20){const r=rows.slice(-p);let pv=0,v=0;for(const x of r){const tp=(x.high+x.low+x.close)/3;pv+=tp*x.volume;v+=x.volume}return v?pv/v:null}
function pct(a,b){return a!=null&&b?((a/b)-1)*100:null}
function scoreTechnical(t){let s=50,why=[];if(t.last>t.ema20){s+=7;why.push('Price above EMA20')}else{s-=7;why.push('Price below EMA20')}if(t.ema20>t.ema50){s+=8;why.push('EMA20 above EMA50')}else{s-=8;why.push('EMA20 below EMA50')}if(t.ema50>t.ema200){s+=8;why.push('EMA50 above EMA200')}else{s-=8;why.push('EMA50 below EMA200')}if(t.rsi!=null){if(t.rsi>=55&&t.rsi<=72){s+=7;why.push('RSI confirms momentum')}else if(t.rsi>75){s-=3;why.push('RSI overheated')}else if(t.rsi<40){s-=6;why.push('RSI weak')}}if(t.macd?.histogram!=null){if(t.macd.histogram>0){s+=7;why.push('MACD positive')}else{s-=7;why.push('MACD negative')}}if(t.adx!=null){if(t.adx>=25)s+=6;else if(t.adx<18)s-=3}if(t.relativeVolume!=null&&t.relativeVolume>=1.2)s+=5;return {score:clamp(s),why}}
function makeTrade(a,tech){const p=tech.last,atrv=tech.atr||p*.02,support=tech.support,resistance=tech.resistance;const base={entry:null,breakout:null,stopLoss:null,target1:null,target2:null,riskReward:null};
const longBias=tech.score>=65&&tech.trend!=='DOWNTREND', shortBias=tech.score<=38&&tech.trend==='DOWNTREND';
if(longBias){const entryLow=support&&support<p?p*.985:support||p-atrv*.6,entryHigh=p;const sl=Math.min(entryLow-atrv*.6,p-1.5*atrv);const t1=resistance&&resistance>p?resistance:p+2*atrv;const t2=Math.max(t1+atrv*1.5,p+3.5*atrv);base.entry={low:entryLow,high:entryHigh};base.breakout=resistance&&resistance>p?resistance:null;base.stopLoss=sl;base.target1=t1;base.target2=t2;base.riskReward=(t1-p)/(p-sl);}
else if(shortBias){const sl=p+1.5*atrv,t1=support&&support<p?support:p-2*atrv,t2=Math.min(t1-atrv*1.5,p-3.5*atrv);base.entry={low:p,high:p};base.stopLoss=sl;base.target1=t1;base.target2=t2;base.riskReward=(p-t1)/(sl-p)}
let action='NO TRADE',reason='Signals are mixed.';if(longBias&&tech.rsi!=null&&tech.rsi<78){action='BUY';reason='Trend, momentum and structure are aligned.'}else if(shortBias){action='SELL';reason='Trend and momentum are bearish.'}else if(tech.trend!=='DOWNTREND'&&tech.rsi!=null&&tech.rsi<45){action='BUY ON PULLBACK';reason='Trend is constructive but momentum needs a better entry.'}else if(tech.trend==='UPTREND'){action='HOLD / WAIT';reason='Trend is positive but current confirmation is not strong enough for a fresh entry.'}return {...base,action,reason}}
function buildTrading(analysis,rows){const clean=rows.filter(x=>n(x.close)!=null&&n(x.high)!=null&&n(x.low)!=null&&n(x.volume)!=null),c=clean.map(x=>x.close),last=c.at(-1);const e20=ema(c,20),e50=ema(c,50),e200=ema(c,200),s20=sma(c,20),s50=sma(c,50),s200=sma(c,200),rr=rsi(c),aa=atr(clean),mm=macd(c),ad=adx(clean),vw=vwap(clean),avgV=sma(clean.map(x=>x.volume),20),rv=avgV?clean.at(-1).volume/avgV:null;const hi20=Math.max(...clean.slice(-20).map(x=>x.high)),lo20=Math.min(...clean.slice(-20).map(x=>x.low)),hi52=Math.max(...clean.slice(-252).map(x=>x.high)),lo52=Math.min(...clean.slice(-252).map(x=>x.low));const trend=e200!=null?(last>e20&&e20>e50&&e50>e200?'STRONG UPTREND':last>e50&&e50>e200?'UPTREND':last<e50&&e50<e200?'DOWNTREND':'MIXED'):(e50!=null&&last>e50?'UPTREND':'MIXED');const tech={last,e20:e20,e50:e50,e200:e200,s20,s50,s200,rsi:rr,atr:aa,macd:mm,adx:ad,vwap:vw,relativeVolume:rv,support:lo20,resistance:hi20,high52:hi52,low52:lo52,trend,change1d:pct(last,c.at(-2)),change20d:pct(last,c.at(-21)),change3m:pct(last,c.at(-64)),distance200:e200?pct(last,e200):null};const st=scoreTechnical(tech);tech.score=st.score;tech.why=st.why;const trade=makeTrade(analysis,tech);
const f=analysis.fundamentals||{},r=f.ratios||{},g=f.growth||{},v=analysis.valuation||{},sc=analysis.score||{},dq=analysis.dataQuality||{};const fundamental=clamp(50+(Number(sc.overall)||50)*.5+(Number(r.roe)||0)*.15);const valuation=v.verdict==='UNDERVALUED'?85:v.verdict==='FAIRLY VALUED'?70:v.verdict==='EXPENSIVE'?45:v.verdict==='VERY EXPENSIVE'?25:55;const risk=clamp(100-(Number(sc.risk)||50));const longScore=clamp(fundamental*.55+valuation*.25+risk*.20);let longAction=longScore>=78?'BUY':longScore>=68?'ACCUMULATE':longScore>=55?'HOLD':longScore>=45?'REDUCE':'SELL';if((dq.confidence??0)<60)longAction='DATA INSUFFICIENT';const long={score:Math.round(longScore),action:longAction,fundamental:Math.round(fundamental),valuation,financialStrength:Math.round(risk),buyBelow:v.baseFairValue?Number(v.baseFairValue)*.9:null,fairValue:v.baseFairValue??v.fairValue??null,reason:longAction==='BUY'?'Quality, valuation and financial strength support accumulation.':longAction==='ACCUMULATE'?'Business quality is acceptable; prefer valuation discipline.':longAction==='SELL'?'Risk/quality combination is not supportive.':'Evidence does not justify an aggressive new position.'};
return {symbol:analysis.stock?.symbol,price:last,currency:'INR',asOf:new Date().toISOString(),chart:clean.slice(-180),technical:tech,trade,periods:{longTerm:'3–10Y',swing:'2–20D',shortTerm:'1–5D'},longTerm:long,meta:{dataConfidence:dq.confidence??null,source:'Yahoo Finance chart + StockSamjho deterministic analysis'}}}
export {buildTrading};
