import {isRateLimited} from '../lib/cache.js';
const CACHE=new Map(),TTL=3*60*60*1000,MAX=400,H={'User-Agent':'Mozilla/5.0','Accept':'application/json','Referer':'https://finance.yahoo.com/'};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function cors(res){res.setHeader('Access-Control-Allow-Origin',process.env.ALLOWED_ORIGIN||'*');res.setHeader('Access-Control-Allow-Methods','POST, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Cache-Control','no-store')}
function send(res,s,b){cors(res);return res.status(s).json(b)}
function ticker(v){const x=String(v||'').trim().toUpperCase();if(!x||!/^[A-Z0-9._&-]{1,25}$/.test(x))return'';return x.endsWith('.NS')||x.endsWith('.BO')||x.startsWith('^')?x:x+'.NS'}
function get(k){const x=CACHE.get(k);if(!x||Date.now()>x.e){CACHE.delete(k);return null}return x.d}function set(k,d){if(CACHE.size>=MAX)CACHE.delete(CACHE.keys().next().value);CACHE.set(k,{d,e:Date.now()+TTL})}
async function yf(url,tries=2){let last;for(let i=1;i<=tries;i++){const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);try{const r=await fetch(url,{headers:H,signal:c.signal}),txt=await r.text();clearTimeout(t);if(r.status===429||/too many requests/i.test(txt)){last=new Error('RATE_LIMIT');if(i<tries){await sleep(2000*i);continue}throw last}if(!r.ok)throw new Error('HTTP_'+r.status);return JSON.parse(txt)}catch(e){clearTimeout(t);last=e?.name==='AbortError'?new Error('TIMEOUT'):e;if(i<tries)await sleep(1200*i)}}throw last||new Error('DATA_FETCH_FAILED')}
async function chart(v,range='1y',interval='1d'){const s=ticker(v);if(!s)throw Error('Invalid ticker');const k=`c:${s}:${range}:${interval}`,old=get(k);if(old)return old;const j=await yf(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(s)}?range=${range}&interval=${interval}&events=div%2Csplits`),r=j?.chart?.result?.[0];if(!r)throw Error('No market data found');const q=r.indicators?.quote?.[0]||{},a=r.indicators?.adjclose?.[0]?.adjclose||[],o={ticker:s,currency:r.meta?.currency||'INR',exchange:r.meta?.exchangeName||'',regularMarketPrice:r.meta?.regularMarketPrice??null,timestamps:r.timestamp||[],open:q.open||[],high:q.high||[],low:q.low||[],close:q.close||[],volume:q.volume||[],adjclose:a};set(k,o);return o}
async function summary(v){const s=ticker(v),k=`s:${s}`,old=get(k);if(old)return old;const c=await chart(s),cl=c.close.filter(Number.isFinite),hi=c.high.filter(Number.isFinite),lo=c.low.filter(Number.isFinite),vo=c.volume.filter(Number.isFinite);const o={symbol:s,price:c.regularMarketPrice??cl.at(-1)??null,currency:c.currency,exchange:c.exchange,previousClose:cl.at(-2)??null,fiftyTwoWeekHigh:hi.length?Math.max(...hi):null,fiftyTwoWeekLow:lo.length?Math.min(...lo):null,averageVolume:vo.length?vo.reduce((a,b)=>a+b,0)/vo.length:null,volume:vo.at(-1)??null,chart:c,fundamentals:{note:'Full fundamentals require a reliable fundamentals provider; do not infer missing ROE, debt, margins, promoter or cash-flow values.'}};set(k,o);return o}
async function news(q){q=String(q||'').trim();if(!q)throw Error('query required');const k='n:'+q.toLowerCase(),old=get(k);if(old)return old;const j=await yf(`https://query1.finance.yahoo.com/v1/finance/search?q=${encodeURIComponent(q)}&newsCount=10&quotesCount=5`),a=(j?.news||[]).map(n=>({title:n.title||'',publisher:n.publisher||'',link:n.link||n.url||'#',publishedAt:n.providerPublishTime?new Date(n.providerPublishTime*1000).toISOString():''}));set(k,a);return a}
function avg(a,n){const x=a.slice(-n).filter(Number.isFinite);return x.length===n?x.reduce((p,c)=>p+c,0)/n:null}
function ema(a,n){const x=a.filter(Number.isFinite);if(x.length<n)return null;let e=x.slice(0,n).reduce((p,c)=>p+c,0)/n,k=2/(n+1);for(let i=n;i<x.length;i++)e=x[i]*k+e*(1-k);return e}
function rsi(a,n=14){const x=a.filter(Number.isFinite);if(x.length<n+1)return null;let g=0,l=0;for(let i=1;i<=n;i++){const d=x[i]-x[i-1];if(d>=0)g+=d;else l-=d}let ag=g/n,al=l/n;for(let i=n+1;i<x.length;i++){const d=x[i]-x[i-1];ag=(ag*(n-1)+Math.max(d,0))/n;al=(al*(n-1)+Math.max(-d,0))/n}if(al===0)return 100;return 100-(100/(1+ag/al))}
function atr(h,l,c,n=14){if(h.length<n+1)return null;const tr=[];for(let i=1;i<h.length;i++)tr.push(Math.max(h[i]-l[i],Math.abs(h[i]-c[i-1]),Math.abs(l[i]-c[i-1])));return avg(tr,n)}
function technicalSignal(c,bench){
 const close=c.close,high=c.high,low=c.low,vol=c.volume,last=close.at(-1),prev=close.at(-2),s20=avg(close,20),s50=avg(close,50),s200=avg(close,200),r=rsi(close),a=atr(high,low,close),v20=avg(vol,20),recentHigh=Math.max(...high.slice(-20,-1));
 if(!Number.isFinite(last)||!Number.isFinite(s20)||!Number.isFinite(s50)||!Number.isFinite(r)||!Number.isFinite(a)||!Number.isFinite(v20))return null;
 const ret20=close.length>20?last/close.at(-21)-1:null,bret20=bench?.length>20?bench.at(-1)/bench.at(-21)-1:null,rel=Number.isFinite(ret20)&&Number.isFinite(bret20)?ret20-bret20:null;
 const breakout=last>recentHigh,pullback=last>s20&&last<=recentHigh*1.02;
 const trend=s200?(last>s20&&s20>s50&&s50>s200?'BULLISH':last<s20&&s20<s50&&s50<s200?'BEARISH':'MIXED'):(last>s20&&s20>s50?'BULLISH':last<s20&&s20<s50?'BEARISH':'MIXED');
 let score=0;const reasons=[];
 if(trend==='BULLISH'){score+=25;reasons.push('trend aligned')}else if(trend==='MIXED')score+=10;
 if(last>s20){score+=10;reasons.push('above SMA20')}if(s20>s50){score+=10;reasons.push('SMA20 above SMA50')}if(Number.isFinite(s200)&&s50>s200){score+=10;reasons.push('long-term trend positive')}
 if(r>=55&&r<=72){score+=12;reasons.push('RSI healthy')}else if(r>72)score-=8;else if(r<45)score-=10;
 if(vol.at(-1)>=v20*1.2){score+=12;reasons.push('volume confirmation')}else if(vol.at(-1)>=v20)score+=5;
 if(breakout){score+=14;reasons.push('20D breakout')}else if(pullback){score+=7;reasons.push('controlled pullback')}
 if(Number.isFinite(rel)){if(rel>0.03){score+=12;reasons.push('relative strength')}else if(rel>0)score+=5;else score-=6}
 score=Math.max(0,Math.min(100,Math.round(score)));
 const confirmed=trend==='BULLISH'&&last>s20&&s20>s50&&r>=55&&r<=72&&(breakout||pullback)&&vol.at(-1)>=v20&&(!Number.isFinite(rel)||rel>0);
 const action=confirmed&&score>=78?'TOP OPPORTUNITY':score>=65?'WATCHLIST':'NO SETUP';
 return {price:last,momentumPct:prev?((last-prev)/prev)*100:0,sma20:s20,sma50:s50,sma200:s200,rsi14:r,atr14:a,volumeRatio:v20?vol.at(-1)/v20:null,breakout20:breakout,trend,relativeStrength20Pct:Number.isFinite(rel)?rel*100:null,score,action,technicalConfirmation:confirmed,reasons};
}
async function scan(limit=25){const ss=['RELIANCE','TCS','HDFCBANK','ICICIBANK','INFY','ITC','LT','BHARTIARTL','AXISBANK','MARUTI','SUNPHARMA','M&M','TITAN','BAJFINANCE','KOTAKBANK','TRENT','HAL','BEL','POLYCAB','HAVELLS','PIDILITIND','DIXON','POWERGRID','NTPC','COALINDIA','TATASTEEL','JSWSTEEL','HCLTECH','TECHM','PERSISTENT','DRREDDY','CIPLA','APOLLOHOSP','ADANIENT','ADANIPORTS','SBIN','INDUSINDBK','BAJAJFINSV','EICHERMOT','TVSMOTOR'].slice(0,Math.max(1,Math.min(Number(limit)||25,40)));let bench=[];try{const b=await chart('^NSEI','6mo','1d');bench=b.close.filter(Number.isFinite)}catch{}const out=[];for(const s of ss)try{const c=await chart(s,'6mo','1d');if(c.close.filter(Number.isFinite).length<200)continue;const sig=technicalSignal(c,bench);if(sig)out.push({symbol:c.ticker,...sig,dataConfidence:'HIGH — verified OHLCV',source:'Yahoo Finance chart API',asOf:c.timestamps?.at(-1)?new Date(c.timestamps.at(-1)*1000).toISOString():null})}catch{}out.sort((a,b)=>b.score-a.score);return {generatedAt:new Date().toISOString(),universeSize:ss.length,scanned:out.length,method:'TECHNICAL_OPPORTUNITY_RANKING',note:'Ranking identifies evidence-backed technical opportunities. It does not override fundamental/strategy production gates and never fabricates BUY/SELL.',results:out}}
export default async function handler(req,res){cors(res);if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST')return send(res,405,{error:'POST only'});const ip=req.headers['x-forwarded-for']?.split(',')[0]?.trim()||'unknown',rate=isRateLimited(ip);if(rate.limited)return send(res,429,{error:'Rate limit exceeded',resetAt:rate.resetAt});try{const b=typeof req.body==='string'?JSON.parse(req.body):(req.body||{});if(!b.type)return send(res,400,{error:'type required: summary|chart|news|scan'});if(b.type==='summary')return send(res,200,await summary(b.ticker));if(b.type==='chart')return send(res,200,await chart(b.ticker,b.range||'1y',b.interval||'1d'));if(b.type==='news')return send(res,200,await news(b.query||b.ticker));if(b.type==='scan')return send(res,200,await scan(b.limit));return send(res,400,{error:'Unknown type'})}catch(e){return send(res,500,{error:e.message||'Backend error'})}}
