import { scanSymbols, DEFAULT_UNIVERSE } from '../lib/scanner-engine-v2.js';
import { analyzeVerified } from '../lib/verified-analysis.js';
import { cacheGet, cacheSet } from '../lib/cache.js';
import { gateTradingAction, productionDecisionPolicy } from '../lib/production-decision-gate.js';
const CORS={'Access-Control-Allow-Origin':process.env.ALLOWED_ORIGIN||'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Cache-Control':'no-store'};
const SCAN_CACHE_TTL=2*60*1000;
const send=(res,status,body)=>{Object.entries(CORS).forEach(([k,v])=>res.setHeader(k,v));return res.status(status).json(body)};
const withTimeout=(p,ms)=>Promise.race([p,new Promise((_,rej)=>setTimeout(()=>rej(new Error('TIMEOUT')),ms))]);
function uiResult(x){const setup=x.setup||{},why=Array.isArray(x.why)?x.why:(x.evidence||[]),rawValuation=x.deep?.valuation||'DATA INSUFFICIENT',score=x.strategyScore??setup.strategyScore??null,risk=x.riskRewardScore??setup.riskRewardScore??null,confidence=x.confidence??setup.confidence??null,reason=why.slice(0,3).join(' • ')||'No separate evidence available';return {...x,score,risk,confidence,action:setup.action??x.deep?.decision??'WAIT',valuation:`${rawValuation} | Confidence ${confidence??'—'}/100 | Why: ${reason}`,trend:x.technical?.trend??'—',reason,ui:{strategyScore:score,riskRewardScore:risk,confidence,why:why.slice(0,5)}}}
async function enrichDeep(rows){const candidates=rows.slice(0,5),out=[];let i=0;async function worker(){while(i<candidates.length){const item=candidates[i++];try{const d=await withTimeout(analyzeVerified(item.symbol),8000);const s=d?.score||{},v=d?.valuation||{},q=d?.dataQuality||{};out.push({...item,deep:{overall:s.overall??null,risk:s.risk??null,confidence:q.confidence??null,dataLimited:Boolean(s.dataLimited),valuation:v.verdict??'DATA INSUFFICIENT',decision:d?.decision?.action??'WAIT',fairValue:v.fairValue??null,marginOfSafety:v.marginOfSafety??null,verifiedMarketAsOf:d?.provenance?.marketData?.asOf??null,verifiedFundamentalsAsOf:d?.provenance?.statementEvidence?.asOf??null}})}catch(error){out.push({...item,deep:{status:'UNAVAILABLE',error:error?.message||'Deep analysis unavailable'}})}}}await Promise.all(Array.from({length:2},worker));return out.sort((a,b)=>(b.deep?.overall??-1)-(a.deep?.overall??-1))}
function gateScanResult(x){const setup=x.setup||{};return {...x,setup:{...setup,action:gateTradingAction(setup.action)},deep:x.deep?{...x.deep,decision:gateTradingAction(x.deep.decision)}:x.deep}}
export default async function handler(req,res){if(req.method==='OPTIONS')return send(res,204,{});if(req.method!=='GET'&&req.method!=='POST')return send(res,405,{success:false,error:'Method not allowed'});try{let symbols=DEFAULT_UNIVERSE,deep=false;if(req.method==='GET'){if(req.query?.symbols)symbols=String(req.query.symbols).split(',').map(x=>x.trim()).filter(Boolean);deep=String(req.query?.deep||'false')==='true'}if(req.method==='POST'){const b=typeof req.body==='string'?JSON.parse(req.body):req.body||{};if(Array.isArray(b.symbols)&&b.symbols.length)symbols=b.symbols;deep=b.deep===true}const key=`tomorrow-scan-v5:${deep?'deep:':''}${symbols.map(String).sort().join(',')}`;const cached=cacheGet(key);if(cached)return send(res,200,{...cached,cached:true});const broad=await withTimeout(scanSymbols(symbols),25000);let results=(broad.results||[]).map(uiResult);if(deep)results=await enrichDeep(results);results=results.map(gateScanResult).map(uiResult);const policy=productionDecisionPolicy();const readyList=policy.productionActionsEnabled?(broad.readyList||[]):[];const payload={...broad,results,readyCount:readyList.length,readyList,mode:deep?'BROAD+DEEP_VERIFIED':'BROAD_TECHNICAL',decisionPolicy:{...policy,decisionBasis:'Verified data only. Missing evidence excludes a stock from a ready action. No fallback or fabricated values.'},uiContract:{score:'strategyScore',risk:'riskRewardScore',confidence:'confidence',reason:'why/evidence',action:'setup.action'}};cacheSet(key,payload,SCAN_CACHE_TTL);return send(res,200,{...payload,cached:false})}catch(error){console.error('[SCAN ERROR]',error?.message);return send(res,502,{success:false,scanned:0,readyCount:0,readyList:[],results:[],errors:[{error:error?.message||'SCANNER_UNAVAILABLE'}],dataStatus:'UNAVAILABLE',policy:{fakeDataAllowed:false,missingDataAction:'RETURN_ERROR_NOT_FALLBACK'}})}}
