import YahooFinance from 'yahoo-finance2';
import { analyze as analyzeStock } from '../lib/market-engine.js';
import { buildTrading } from '../lib/trading-engine.js';
import { gateTradingAction, productionDecisionPolicy } from '../lib/production-decision-gate.js';
const yahooFinance=new YahooFinance();
const HEADERS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,OPTIONS','Cache-Control':'no-store'};
const num=v=>{if(typeof v==='number'&&Number.isFinite(v))return v;if(v&&typeof v==='object'&&Number.isFinite(v.raw))return v.raw;return null};
const unavailable=e=>/no data found|symbol may be delisted|insufficient market data/i.test(String(e?.message||''));
async function fetchChart(symbol){const ticker=String(symbol).endsWith('.NS')||String(symbol).endsWith('.BO')?String(symbol):`${symbol}.NS`;const data=await yahooFinance.chart(ticker,{period1:new Date(Date.now()-2*365.25*24*60*60*1000),period2:new Date(),interval:'1d',events:'div,splits',return:'object'});const rows=[];if(Array.isArray(data?.quotes)){for(const item of data.quotes){const close=num(item?.close),high=num(item?.high),low=num(item?.low),volume=num(item?.volume);if(close!=null&&high!=null&&low!=null&&volume!=null){const date=item.date instanceof Date?item.date:new Date(item.date);if(!Number.isNaN(date.getTime()))rows.push({date:date.toISOString(),open:num(item?.open),close,high,low,volume})}}}else{const timestamps=data?.timestamp||[],q=data?.indicators?.quote?.[0]||{};for(let i=0;i<timestamps.length;i++){const close=num(q.close?.[i]),high=num(q.high?.[i]),low=num(q.low?.[i]),volume=num(q.volume?.[i]);if(close!=null&&high!=null&&low!=null&&volume!=null)rows.push({date:new Date(timestamps[i]*1000).toISOString(),open:num(q.open?.[i]),close,high,low,volume})}}if(rows.length<60)throw Error(`Insufficient market data (${rows.length} points)`);return rows}
export default async function handler(req,res){Object.entries(HEADERS).forEach(([k,v])=>res.setHeader(k,v));if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});const symbol=String(req.query?.symbol||'').trim().toUpperCase();if(!/^[A-Za-z0-9.&_-]{1,25}(?:\.(?:NS|BO))?$/i.test(symbol))return res.status(400).json({error:'Valid stock symbol is required'});try{const analysis=await analyzeStock(symbol);const rows=await fetchChart(symbol);const result=buildTrading(analysis,rows);const gatedTrade={...result.trade,action:gateTradingAction(result.trade?.action)};const gatedLongTerm={...result.longTerm,action:gateTradingAction(result.longTerm?.action)};const decisionPolicy=productionDecisionPolicy();
// The legacy UI derives its short-term action from technical.score. Keep that
// legacy path fail-closed while production BUY/SELL is disabled: a production
// action must come from the backend gate, never from a second client-side rule.
const productionSafeTechnical=decisionPolicy.productionActionsEnabled
  ? result.technical
  : {...result.technical,score:null,productionDecisionBlocked:true};
return res.status(200).json({...result,technical:productionSafeTechnical,trade:gatedTrade,longTerm:gatedLongTerm,decisionPolicy})}catch(e){if(unavailable(e)){console.warn('[TRADING DATA UNAVAILABLE]',{symbol,message:e?.message});return res.status(404).json({success:false,error:'Verified market data is unavailable for this symbol.'})}console.error('[TRADING ERROR]',{symbol,message:e?.message,stack:e?.stack});return res.status(502).json({error:'Trading data temporarily unavailable. Please try again.'})}}
