import { analyzeVerified } from '../lib/verified-analysis.js';
import { verifiedHistory } from '../lib/market-data-provider.js';
import { buildTrading } from '../lib/trading-engine.js';
import { gateTradingAction, productionDecisionPolicy } from '../lib/production-decision-gate.js';
const HEADERS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,OPTIONS','Cache-Control':'no-store'};
const unavailable=e=>/no data found|symbol may be delisted|insufficient market data|verified market data unavailable/i.test(String(e?.message||''));
export default async function handler(req,res){Object.entries(HEADERS).forEach(([k,v])=>res.setHeader(k,v));if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});const symbol=String(req.query?.symbol||'').trim().toUpperCase();if(!/^[A-Za-z0-9.&_-]{1,25}(?:\.(?:NS|BO))?$/i.test(symbol))return res.status(400).json({error:'Valid stock symbol is required'});try{const [analysis,history]=await Promise.all([analyzeVerified(symbol),verifiedHistory(symbol,{interval:'1d',days:900,minBars:60})]);const rows=history.rows.map(row=>({date:row.date,open:row.o,close:row.c,high:row.h,low:row.l,volume:row.v}));const result=buildTrading(analysis,rows);const gatedTrade={...result.trade,action:gateTradingAction(result.trade?.action)};const gatedLongTerm={...result.longTerm,action:gateTradingAction(result.longTerm?.action)};const decisionPolicy=productionDecisionPolicy();
const productionSafeTechnical=decisionPolicy.productionActionsEnabled
  ? result.technical
  : {...result.technical,score:analysis?.score?.technical??null,productionDecisionBlocked:true};
return res.status(200).json({...result,technical:productionSafeTechnical,trade:gatedTrade,longTerm:gatedLongTerm,decisionPolicy,provenance:analysis.provenance})}catch(e){if(unavailable(e)){console.warn('[TRADING DATA UNAVAILABLE]',{symbol,message:e?.message});return res.status(404).json({success:false,error:'Verified market data is unavailable for this symbol.'})}console.error('[TRADING ERROR]',{symbol,message:e?.message,stack:e?.stack});return res.status(502).json({error:'Trading data temporarily unavailable. Please try again.'})}}
